# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class IpPoolServiceRangeList:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def ip_pool_service_range_list(
        self,
        limit: Optional[int] = None,
        page_token: Optional[str] = None,
    ) -> Any:
        """
        Ranges are ordered by their first address.

        Args:
            limit: Maximum number of items returned by a single call
            page_token: Token returned by previous call to retrieve the subsequent page

        Returns:
            Response data
        """
        path = f"/v1/system/ip-pools-service/ranges"
        params = {}
        headers = {}
        if limit is not None:
            params["limit"] = limit
        if page_token is not None:
            params["page_token"] = page_token
        json_data = None

        response = self.parent._make_request(
            method="GET",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
