# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class SledAdd:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def sled_add(
        self,
        part: str,
        serial: str,
    ) -> Any:
        """


        Args:
            part: The unique hardware ID for a sled
            serial: The unique hardware ID for a sled

        Returns:
            Response data
        """
        path = f"/v1/system/hardware/sleds"
        params = None
        headers = None
        json_data = {
            "part": part if part is not None else None,
            "serial": serial if serial is not None else None,
        }
        json_data = {k: v for k, v in json_data.items() if v is not None}

        response = self.parent._make_request(
            method="POST",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
