# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ...models.models import *

from .ip_pool_list.ip_pool_list import IpPoolList
from .ip_pool_create.ip_pool_create import IpPoolCreate
from .ip_pool_view.ip_pool_view import IpPoolView
from .ip_pool_update.ip_pool_update import IpPoolUpdate
from .ip_pool_delete.ip_pool_delete import IpPoolDelete
from .ip_pool_range_list.ip_pool_range_list import IpPoolRangeList
from .ip_pool_range_add.ip_pool_range_add import IpPoolRangeAdd
from .ip_pool_range_remove.ip_pool_range_remove import IpPoolRangeRemove
from .ip_pool_silo_list.ip_pool_silo_list import IpPoolSiloList
from .ip_pool_silo_link.ip_pool_silo_link import IpPoolSiloLink
from .ip_pool_silo_update.ip_pool_silo_update import IpPoolSiloUpdate
from .ip_pool_silo_unlink.ip_pool_silo_unlink import IpPoolSiloUnlink
from .ip_pool_utilization_view.ip_pool_utilization_view import IpPoolUtilizationView
from .ip_pool_service_view.ip_pool_service_view import IpPoolServiceView
from .ip_pool_service_range_list.ip_pool_service_range_list import (
    IpPoolServiceRangeList,
)
from .ip_pool_service_range_add.ip_pool_service_range_add import IpPoolServiceRangeAdd
from .ip_pool_service_range_remove.ip_pool_service_range_remove import (
    IpPoolServiceRangeRemove,
)

if TYPE_CHECKING:
    from ..oxide_region_api import OxideRegionAPI


class SystemIpPools:
    def __init__(self, parent: "OxideRegionAPI"):
        """
        IP pools are collections of external IPs that can be assigned to silos. When a pool is linked to a silo, users in that silo can allocate IPs from the pool for their instances.

        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.ip_pool_list = IpPoolList(parent=parent).ip_pool_list
        self.ip_pool_create = IpPoolCreate(parent=parent).ip_pool_create
        self.ip_pool_view = IpPoolView(parent=parent).ip_pool_view
        self.ip_pool_update = IpPoolUpdate(parent=parent).ip_pool_update
        self.ip_pool_delete = IpPoolDelete(parent=parent).ip_pool_delete
        self.ip_pool_range_list = IpPoolRangeList(parent=parent).ip_pool_range_list
        self.ip_pool_range_add = IpPoolRangeAdd(parent=parent).ip_pool_range_add
        self.ip_pool_range_remove = IpPoolRangeRemove(
            parent=parent
        ).ip_pool_range_remove
        self.ip_pool_silo_list = IpPoolSiloList(parent=parent).ip_pool_silo_list
        self.ip_pool_silo_link = IpPoolSiloLink(parent=parent).ip_pool_silo_link
        self.ip_pool_silo_update = IpPoolSiloUpdate(parent=parent).ip_pool_silo_update
        self.ip_pool_silo_unlink = IpPoolSiloUnlink(parent=parent).ip_pool_silo_unlink
        self.ip_pool_utilization_view = IpPoolUtilizationView(
            parent=parent
        ).ip_pool_utilization_view
        self.ip_pool_service_view = IpPoolServiceView(
            parent=parent
        ).ip_pool_service_view
        self.ip_pool_service_range_list = IpPoolServiceRangeList(
            parent=parent
        ).ip_pool_service_range_list
        self.ip_pool_service_range_add = IpPoolServiceRangeAdd(
            parent=parent
        ).ip_pool_service_range_add
        self.ip_pool_service_range_remove = IpPoolServiceRangeRemove(
            parent=parent
        ).ip_pool_service_range_remove
