# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class DeviceAuthConfirm:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def device_auth_confirm(
        self,
        user_code: str,
    ) -> Any:
        """
        This endpoint is designed to be accessed by the user agent (browser), not the client requesting the token. So we do not actually return the token here; it will be returned in response to the poll on `/device/token`.

        Args:
            user_code: No description provided

        Returns:
            Response data
        """
        path = f"/device/confirm"
        params = None
        headers = None
        json_data = {
            "user_code": user_code if user_code is not None else None,
        }
        json_data = {k: v for k, v in json_data.items() if v is not None}

        response = self.parent._make_request(
            method="POST",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
