# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ...models.models import *

from .snapshot_list.snapshot_list import SnapshotList
from .snapshot_create.snapshot_create import SnapshotCreate
from .snapshot_view.snapshot_view import SnapshotView
from .snapshot_delete.snapshot_delete import SnapshotDelete

if TYPE_CHECKING:
    from ..oxide_region_api import OxideRegionAPI


class Snapshots:
    def __init__(self, parent: "OxideRegionAPI"):
        """
        Snapshots of virtual disks at a particular point in time.

        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.snapshot_list = SnapshotList(parent=parent).snapshot_list
        self.snapshot_create = SnapshotCreate(parent=parent).snapshot_create
        self.snapshot_view = SnapshotView(parent=parent).snapshot_view
        self.snapshot_delete = SnapshotDelete(parent=parent).snapshot_delete
