# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class SamlIdentityProviderView:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def saml_identity_provider_view(
        self,
        provider: NameOrId,
        silo: NameOrId,
    ) -> Any:
        """


        Args:
            provider: Name or ID of the SAML identity provider
            silo: Name or ID of the silo

        Returns:
            Response data
        """
        path = f"/v1/system/identity-providers/saml/{provider}"
        params = {}
        headers = {}
        if silo is not None:
            params["silo"] = silo
        json_data = None

        response = self.parent._make_request(
            method="GET",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
