# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ...models.models import *

from .login_saml.login_saml import LoginSaml
from .login_local.login_local import LoginLocal

if TYPE_CHECKING:
    from ..oxide_region_api import OxideRegionAPI


class Login:
    def __init__(self, parent: "OxideRegionAPI"):
        """
        Authentication endpoints

        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.login_saml = LoginSaml(parent=parent).login_saml
        self.login_local = LoginLocal(parent=parent).login_local
