# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class VpcSubnetUpdate:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def vpc_subnet_update(
        self,
        subnet: NameOrId,
        project: Optional[NameOrId] = None,
        vpc: Optional[NameOrId] = None,
        custom_router: Optional[NameOrId] = None,
        description: Optional[str] = None,
        name: Optional[Name] = None,
    ) -> Any:
        """


        Args:
            subnet: Name or ID of the subnet
            project: Name or ID of the project, only required if `vpc` is provided as a `Name`
            vpc: Name or ID of the VPC
            custom_router: No description provided
            description: Updateable properties of a `VpcSubnet`
            name: Names must begin with a lower case ASCII letter, be composed exclusively of lowercase ASCII, uppercase ASCII, numbers, and '-', and may not end with a '-'. Names cannot be a UUID, but they may contain a UUID. They can be at most 63 characters long.

        Returns:
            Response data
        """
        path = f"/v1/vpc-subnets/{subnet}"
        params = {}
        headers = {}
        if project is not None:
            params["project"] = project
        if vpc is not None:
            params["vpc"] = vpc
        json_data = {
            "custom_router": custom_router if custom_router is not None else None,
            "description": description if description is not None else None,
            "name": name if name is not None else None,
        }
        json_data = {k: v for k, v in json_data.items() if v is not None}

        response = self.parent._make_request(
            method="PUT",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
