# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...trieve_api import TrieveApi


class UploadHtmlPage:
    def __init__(self, parent: "TrieveApi"):
        self.parent = parent

    def upload_html_page(
        self,
        data: Document,
        metadata: Any,
        scrapeId: str,
    ) -> Any:
        """
        Chunk HTML by headings and queue for indexing into the specified dataset.

        Args:
            data: No description provided
            metadata: No description provided
            scrapeId: No description provided

        Returns:
            Response data
        """
        path = f"/api/file/html_page"
        params = None
        headers = None
        json_data = {
            "data": data if data is not None else None,
            "metadata": metadata if metadata is not None else None,
            "scrapeId": scrapeId if scrapeId is not None else None,
        }
        json_data = {k: v for k, v in json_data.items() if v is not None}

        response = self.parent._make_request(
            method="POST",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
