# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...trieve_api import TrieveApi


class DeleteInvitation:
    def __init__(self, parent: "TrieveApi"):
        self.parent = parent

    def delete_invitation(
        self,
        tr_organization: str,
        invitation_id: str,
    ) -> Any:
        """
        Delete an invitation by id. Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.

        Args:
            tr_organization: The organization id to use for the request
            invitation_id: The id of the invitation to delete

        Returns:
            Response data
        """
        path = f"/api/invitation/{invitation_id}"
        params = {}
        headers = {}
        if tr_organization is not None:
            headers["TR-Organization"] = tr_organization
        json_data = None

        response = self.parent._make_request(
            method="DELETE",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
