# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ...models.models import *

from .create_chunk.create_chunk import CreateChunk
from .update_chunk.update_chunk import UpdateChunk
from .bulk_delete_chunk.bulk_delete_chunk import BulkDeleteChunk
from .autocomplete.autocomplete import Autocomplete
from .count_chunks.count_chunks import CountChunks
from .generate_off_chunks.generate_off_chunks import GenerateOffChunks
from .get_recommended_chunks.get_recommended_chunks import GetRecommendedChunks
from .search_chunks.search_chunks import SearchChunks
from .split_html_content.split_html_content import SplitHtmlContent
from .get_suggested_queries.get_suggested_queries import GetSuggestedQueries
from .update_chunk_by_tracking_id.update_chunk_by_tracking_id import (
    UpdateChunkByTrackingId,
)
from .get_chunk_by_tracking_id.get_chunk_by_tracking_id import GetChunkByTrackingId
from .delete_chunk_by_tracking_id.delete_chunk_by_tracking_id import (
    DeleteChunkByTrackingId,
)
from .get_chunk_by_id.get_chunk_by_id import GetChunkById
from .delete_chunk.delete_chunk import DeleteChunk
from .get_chunks_by_ids.get_chunks_by_ids import GetChunksByIds
from .scroll_dataset_chunks.scroll_dataset_chunks import ScrollDatasetChunks
from .get_chunks_by_tracking_ids.get_chunks_by_tracking_ids import (
    GetChunksByTrackingIds,
)

if TYPE_CHECKING:
    from ..trieve_api import TrieveApi


class Chunk:
    def __init__(self, parent: "TrieveApi"):
        """
        Chunk endpoint. Think of chunks as individual searchable units of information. The majority of your integration will likely be with the Chunk endpoint.

        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.create_chunk = CreateChunk(parent=parent).create_chunk
        self.update_chunk = UpdateChunk(parent=parent).update_chunk
        self.bulk_delete_chunk = BulkDeleteChunk(parent=parent).bulk_delete_chunk
        self.autocomplete = Autocomplete(parent=parent).autocomplete
        self.count_chunks = CountChunks(parent=parent).count_chunks
        self.generate_off_chunks = GenerateOffChunks(parent=parent).generate_off_chunks
        self.get_recommended_chunks = GetRecommendedChunks(
            parent=parent
        ).get_recommended_chunks
        self.search_chunks = SearchChunks(parent=parent).search_chunks
        self.split_html_content = SplitHtmlContent(parent=parent).split_html_content
        self.get_suggested_queries = GetSuggestedQueries(
            parent=parent
        ).get_suggested_queries
        self.update_chunk_by_tracking_id = UpdateChunkByTrackingId(
            parent=parent
        ).update_chunk_by_tracking_id
        self.get_chunk_by_tracking_id = GetChunkByTrackingId(
            parent=parent
        ).get_chunk_by_tracking_id
        self.delete_chunk_by_tracking_id = DeleteChunkByTrackingId(
            parent=parent
        ).delete_chunk_by_tracking_id
        self.get_chunk_by_id = GetChunkById(parent=parent).get_chunk_by_id
        self.delete_chunk = DeleteChunk(parent=parent).delete_chunk
        self.get_chunks_by_ids = GetChunksByIds(parent=parent).get_chunks_by_ids
        self.scroll_dataset_chunks = ScrollDatasetChunks(
            parent=parent
        ).scroll_dataset_chunks
        self.get_chunks_by_tracking_ids = GetChunksByTrackingIds(
            parent=parent
        ).get_chunks_by_tracking_ids
