# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class InternetGatewayIpPoolCreate:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def internet_gateway_ip_pool_create(
        self,
        gateway: NameOrId,
        description: str,
        ip_pool: NameOrId,
        name: Name,
        project: Optional[NameOrId] = None,
        vpc: Optional[NameOrId] = None,
    ) -> Any:
        """


        Args:
            gateway: Name or ID of the internet gateway
            description: Create-time identity-related parameters
            ip_pool: No description provided
            name: Names must begin with a lower case ASCII letter, be composed exclusively of lowercase ASCII, uppercase ASCII, numbers, and '-', and may not end with a '-'. Names cannot be a UUID, but they may contain a UUID. They can be at most 63 characters long.
            project: Name or ID of the project, only required if `vpc` is provided as a `Name`
            vpc: Name or ID of the VPC, only required if `gateway` is provided as a `Name`

        Returns:
            Response data
        """
        path = f"/v1/internet-gateway-ip-pools"
        params = {}
        headers = {}
        if gateway is not None:
            params["gateway"] = gateway
        if project is not None:
            params["project"] = project
        if vpc is not None:
            params["vpc"] = vpc
        json_data = {
            "description": description if description is not None else None,
            "ip_pool": ip_pool if ip_pool is not None else None,
            "name": name if name is not None else None,
        }
        json_data = {k: v for k, v in json_data.items() if v is not None}

        response = self.parent._make_request(
            method="POST",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
