# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class Ping:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def ping(
        self,
    ) -> Any:
        """
        Always responds with Ok if it responds at all.

        Returns:
            Response data
        """
        path = f"/v1/ping"
        params = None
        headers = None
        json_data = None

        response = self.parent._make_request(
            method="GET",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
