# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class DiskBulkWriteImport:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def disk_bulk_write_import(
        self,
        disk: NameOrId,
        base64_encoded_data: str,
        offset: int,
        project: Optional[NameOrId] = None,
    ) -> Any:
        """


        Args:
            disk: Name or ID of the disk
            base64_encoded_data: Parameters for importing blocks with a bulk write
            offset: Parameters for importing blocks with a bulk write
            project: Name or ID of the project

        Returns:
            Response data
        """
        path = f"/v1/disks/{disk}/bulk-write"
        params = {}
        headers = {}
        if project is not None:
            params["project"] = project
        json_data = {
            "base64_encoded_data": (
                base64_encoded_data if base64_encoded_data is not None else None
            ),
            "offset": offset if offset is not None else None,
        }
        json_data = {k: v for k, v in json_data.items() if v is not None}

        response = self.parent._make_request(
            method="POST",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
