# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class NetworkingAddressLotCreate:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def networking_address_lot_create(
        self,
        blocks: List[AddressLotBlockCreate],
        description: str,
        kind: AddressLotKind,
        name: Name,
    ) -> Any:
        """


        Args:
            blocks: The blocks to add along with the new address lot.
            description: Parameters for creating an address lot.
            kind: Infrastructure address lots are used for network infrastructure like addresses assigned to rack switches.
            name: Names must begin with a lower case ASCII letter, be composed exclusively of lowercase ASCII, uppercase ASCII, numbers, and '-', and may not end with a '-'. Names cannot be a UUID, but they may contain a UUID. They can be at most 63 characters long.

        Returns:
            Response data
        """
        path = f"/v1/system/networking/address-lot"
        params = None
        headers = None
        json_data = {
            "blocks": blocks if blocks is not None else None,
            "description": description if description is not None else None,
            "kind": kind if kind is not None else None,
            "name": name if name is not None else None,
        }
        json_data = {k: v for k, v in json_data.items() if v is not None}

        response = self.parent._make_request(
            method="POST",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
