# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class NetworkingBgpConfigDelete:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def networking_bgp_config_delete(
        self,
        name_or_id: NameOrId,
    ) -> Any:
        """


        Args:
            name_or_id: A name or id to use when selecting BGP config.

        Returns:
            Response data
        """
        path = f"/v1/system/networking/bgp"
        params = {}
        headers = {}
        if name_or_id is not None:
            params["name_or_id"] = name_or_id
        json_data = None

        response = self.parent._make_request(
            method="DELETE",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
