# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class InstanceNetworkInterfaceDelete:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def instance_network_interface_delete(
        self,
        interface: NameOrId,
        instance: Optional[NameOrId] = None,
        project: Optional[NameOrId] = None,
    ) -> Any:
        """
        Note that the primary interface for an instance cannot be deleted if there are any secondary interfaces. A new primary interface must be designated first. The primary interface can be deleted if there are no secondary interfaces.

        Args:
            interface: Name or ID of the network interface
            instance: Name or ID of the instance
            project: Name or ID of the project, only required if `instance` is provided as a `Name`

        Returns:
            Response data
        """
        path = f"/v1/network-interfaces/{interface}"
        params = {}
        headers = {}
        if instance is not None:
            params["instance"] = instance
        if project is not None:
            params["project"] = project
        json_data = None

        response = self.parent._make_request(
            method="DELETE",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
