# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ...models.models import *

from .disk_list.disk_list import DiskList
from .disk_create.disk_create import DiskCreate
from .disk_view.disk_view import DiskView
from .disk_delete.disk_delete import DiskDelete
from .disk_bulk_write_import.disk_bulk_write_import import DiskBulkWriteImport
from .disk_bulk_write_import_start.disk_bulk_write_import_start import (
    DiskBulkWriteImportStart,
)
from .disk_bulk_write_import_stop.disk_bulk_write_import_stop import (
    DiskBulkWriteImportStop,
)
from .disk_finalize_import.disk_finalize_import import DiskFinalizeImport
from .disk_metrics_list.disk_metrics_list import DiskMetricsList

if TYPE_CHECKING:
    from ..oxide_region_api import OxideRegionAPI


class Disks:
    def __init__(self, parent: "OxideRegionAPI"):
        """
        Virtual disks are used to store instance-local data which includes the operating system.

        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.disk_list = DiskList(parent=parent).disk_list
        self.disk_create = DiskCreate(parent=parent).disk_create
        self.disk_view = DiskView(parent=parent).disk_view
        self.disk_delete = DiskDelete(parent=parent).disk_delete
        self.disk_bulk_write_import = DiskBulkWriteImport(
            parent=parent
        ).disk_bulk_write_import
        self.disk_bulk_write_import_start = DiskBulkWriteImportStart(
            parent=parent
        ).disk_bulk_write_import_start
        self.disk_bulk_write_import_stop = DiskBulkWriteImportStop(
            parent=parent
        ).disk_bulk_write_import_stop
        self.disk_finalize_import = DiskFinalizeImport(
            parent=parent
        ).disk_finalize_import
        self.disk_metrics_list = DiskMetricsList(parent=parent).disk_metrics_list
