# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class InternetGatewayIpPoolDelete:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def internet_gateway_ip_pool_delete(
        self,
        pool: NameOrId,
        cascade: Optional[bool] = None,
        gateway: Optional[NameOrId] = None,
        project: Optional[NameOrId] = None,
        vpc: Optional[NameOrId] = None,
    ) -> Any:
        """


        Args:
            pool: Name or ID of the IP pool
            cascade: Also delete routes targeting this gateway element.
            gateway: Name or ID of the internet gateway
            project: Name or ID of the project, only required if `vpc` is provided as a `Name`
            vpc: Name or ID of the VPC, only required if `gateway` is provided as a `Name`

        Returns:
            Response data
        """
        path = f"/v1/internet-gateway-ip-pools/{pool}"
        params = {}
        headers = {}
        if cascade is not None:
            params["cascade"] = cascade
        if gateway is not None:
            params["gateway"] = gateway
        if project is not None:
            params["project"] = project
        if vpc is not None:
            params["vpc"] = vpc
        json_data = None

        response = self.parent._make_request(
            method="DELETE",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
