# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class NetworkingSwitchPortClearSettings:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def networking_switch_port_clear_settings(
        self,
        port: Name,
        rack_id: str,
        switch_location: Name,
    ) -> Any:
        """


        Args:
            port: A name to use when selecting switch ports.
            rack_id: A rack id to use when selecting switch ports.
            switch_location: A switch location to use when selecting switch ports.

        Returns:
            Response data
        """
        path = f"/v1/system/hardware/switch-port/{port}/settings"
        params = {}
        headers = {}
        if rack_id is not None:
            params["rack_id"] = rack_id
        if switch_location is not None:
            params["switch_location"] = switch_location
        json_data = None

        response = self.parent._make_request(
            method="DELETE",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
