# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ...models.models import *

from .internet_gateway_ip_address_list.internet_gateway_ip_address_list import (
    InternetGatewayIpAddressList,
)
from .internet_gateway_ip_address_create.internet_gateway_ip_address_create import (
    InternetGatewayIpAddressCreate,
)
from .internet_gateway_ip_address_delete.internet_gateway_ip_address_delete import (
    InternetGatewayIpAddressDelete,
)
from .internet_gateway_ip_pool_list.internet_gateway_ip_pool_list import (
    InternetGatewayIpPoolList,
)
from .internet_gateway_ip_pool_create.internet_gateway_ip_pool_create import (
    InternetGatewayIpPoolCreate,
)
from .internet_gateway_ip_pool_delete.internet_gateway_ip_pool_delete import (
    InternetGatewayIpPoolDelete,
)
from .internet_gateway_list.internet_gateway_list import InternetGatewayList
from .internet_gateway_create.internet_gateway_create import InternetGatewayCreate
from .internet_gateway_view.internet_gateway_view import InternetGatewayView
from .internet_gateway_delete.internet_gateway_delete import InternetGatewayDelete
from .vpc_firewall_rules_view.vpc_firewall_rules_view import VpcFirewallRulesView
from .vpc_firewall_rules_update.vpc_firewall_rules_update import VpcFirewallRulesUpdate
from .vpc_router_route_list.vpc_router_route_list import VpcRouterRouteList
from .vpc_router_route_create.vpc_router_route_create import VpcRouterRouteCreate
from .vpc_router_route_view.vpc_router_route_view import VpcRouterRouteView
from .vpc_router_route_update.vpc_router_route_update import VpcRouterRouteUpdate
from .vpc_router_route_delete.vpc_router_route_delete import VpcRouterRouteDelete
from .vpc_router_list.vpc_router_list import VpcRouterList
from .vpc_router_create.vpc_router_create import VpcRouterCreate
from .vpc_router_view.vpc_router_view import VpcRouterView
from .vpc_router_update.vpc_router_update import VpcRouterUpdate
from .vpc_router_delete.vpc_router_delete import VpcRouterDelete
from .vpc_subnet_list.vpc_subnet_list import VpcSubnetList
from .vpc_subnet_create.vpc_subnet_create import VpcSubnetCreate
from .vpc_subnet_view.vpc_subnet_view import VpcSubnetView
from .vpc_subnet_update.vpc_subnet_update import VpcSubnetUpdate
from .vpc_subnet_delete.vpc_subnet_delete import VpcSubnetDelete
from .vpc_subnet_list_network_interfaces.vpc_subnet_list_network_interfaces import (
    VpcSubnetListNetworkInterfaces,
)
from .vpc_list.vpc_list import VpcList
from .vpc_create.vpc_create import VpcCreate
from .vpc_view.vpc_view import VpcView
from .vpc_update.vpc_update import VpcUpdate
from .vpc_delete.vpc_delete import VpcDelete

if TYPE_CHECKING:
    from ..oxide_region_api import OxideRegionAPI


class Vpcs:
    def __init__(self, parent: "OxideRegionAPI"):
        """
        Virtual Private Clouds (VPCs) provide isolated network environments for managing and deploying services.

        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.internet_gateway_ip_address_list = InternetGatewayIpAddressList(
            parent=parent
        ).internet_gateway_ip_address_list
        self.internet_gateway_ip_address_create = InternetGatewayIpAddressCreate(
            parent=parent
        ).internet_gateway_ip_address_create
        self.internet_gateway_ip_address_delete = InternetGatewayIpAddressDelete(
            parent=parent
        ).internet_gateway_ip_address_delete
        self.internet_gateway_ip_pool_list = InternetGatewayIpPoolList(
            parent=parent
        ).internet_gateway_ip_pool_list
        self.internet_gateway_ip_pool_create = InternetGatewayIpPoolCreate(
            parent=parent
        ).internet_gateway_ip_pool_create
        self.internet_gateway_ip_pool_delete = InternetGatewayIpPoolDelete(
            parent=parent
        ).internet_gateway_ip_pool_delete
        self.internet_gateway_list = InternetGatewayList(
            parent=parent
        ).internet_gateway_list
        self.internet_gateway_create = InternetGatewayCreate(
            parent=parent
        ).internet_gateway_create
        self.internet_gateway_view = InternetGatewayView(
            parent=parent
        ).internet_gateway_view
        self.internet_gateway_delete = InternetGatewayDelete(
            parent=parent
        ).internet_gateway_delete
        self.vpc_firewall_rules_view = VpcFirewallRulesView(
            parent=parent
        ).vpc_firewall_rules_view
        self.vpc_firewall_rules_update = VpcFirewallRulesUpdate(
            parent=parent
        ).vpc_firewall_rules_update
        self.vpc_router_route_list = VpcRouterRouteList(
            parent=parent
        ).vpc_router_route_list
        self.vpc_router_route_create = VpcRouterRouteCreate(
            parent=parent
        ).vpc_router_route_create
        self.vpc_router_route_view = VpcRouterRouteView(
            parent=parent
        ).vpc_router_route_view
        self.vpc_router_route_update = VpcRouterRouteUpdate(
            parent=parent
        ).vpc_router_route_update
        self.vpc_router_route_delete = VpcRouterRouteDelete(
            parent=parent
        ).vpc_router_route_delete
        self.vpc_router_list = VpcRouterList(parent=parent).vpc_router_list
        self.vpc_router_create = VpcRouterCreate(parent=parent).vpc_router_create
        self.vpc_router_view = VpcRouterView(parent=parent).vpc_router_view
        self.vpc_router_update = VpcRouterUpdate(parent=parent).vpc_router_update
        self.vpc_router_delete = VpcRouterDelete(parent=parent).vpc_router_delete
        self.vpc_subnet_list = VpcSubnetList(parent=parent).vpc_subnet_list
        self.vpc_subnet_create = VpcSubnetCreate(parent=parent).vpc_subnet_create
        self.vpc_subnet_view = VpcSubnetView(parent=parent).vpc_subnet_view
        self.vpc_subnet_update = VpcSubnetUpdate(parent=parent).vpc_subnet_update
        self.vpc_subnet_delete = VpcSubnetDelete(parent=parent).vpc_subnet_delete
        self.vpc_subnet_list_network_interfaces = VpcSubnetListNetworkInterfaces(
            parent=parent
        ).vpc_subnet_list_network_interfaces
        self.vpc_list = VpcList(parent=parent).vpc_list
        self.vpc_create = VpcCreate(parent=parent).vpc_create
        self.vpc_view = VpcView(parent=parent).vpc_view
        self.vpc_update = VpcUpdate(parent=parent).vpc_update
        self.vpc_delete = VpcDelete(parent=parent).vpc_delete
