# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class DiskDelete:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def disk_delete(
        self,
        disk: NameOrId,
        project: Optional[NameOrId] = None,
    ) -> Any:
        """


        Args:
            disk: Name or ID of the disk
            project: Name or ID of the project

        Returns:
            Response data
        """
        path = f"/v1/disks/{disk}"
        params = {}
        headers = {}
        if project is not None:
            params["project"] = project
        json_data = None

        response = self.parent._make_request(
            method="DELETE",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
