# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ...models.models import *

from .project_ip_pool_list.project_ip_pool_list import ProjectIpPoolList
from .project_ip_pool_view.project_ip_pool_view import ProjectIpPoolView
from .project_list.project_list import ProjectList
from .project_create.project_create import ProjectCreate
from .project_view.project_view import ProjectView
from .project_update.project_update import ProjectUpdate
from .project_delete.project_delete import ProjectDelete
from .project_policy_view.project_policy_view import ProjectPolicyView
from .project_policy_update.project_policy_update import ProjectPolicyUpdate

if TYPE_CHECKING:
    from ..oxide_region_api import OxideRegionAPI


class Projects:
    def __init__(self, parent: "OxideRegionAPI"):
        """
        Projects are a grouping of associated resources such as instances and disks within a silo for purposes of billing and access control.

        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.project_ip_pool_list = ProjectIpPoolList(
            parent=parent
        ).project_ip_pool_list
        self.project_ip_pool_view = ProjectIpPoolView(
            parent=parent
        ).project_ip_pool_view
        self.project_list = ProjectList(parent=parent).project_list
        self.project_create = ProjectCreate(parent=parent).project_create
        self.project_view = ProjectView(parent=parent).project_view
        self.project_update = ProjectUpdate(parent=parent).project_update
        self.project_delete = ProjectDelete(parent=parent).project_delete
        self.project_policy_view = ProjectPolicyView(parent=parent).project_policy_view
        self.project_policy_update = ProjectPolicyUpdate(
            parent=parent
        ).project_policy_update
