# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class SupportBundleDownloadFile:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def support_bundle_download_file(
        self,
        file: str,
        support_bundle: str,
    ) -> Any:
        """


        Args:
            file: The file within the bundle to download
            support_bundle: ID of the support bundle

        Returns:
            Response data
        """
        path = (
            f"/experimental/v1/system/support-bundles/{support_bundle}/download/{file}"
        )
        params = {}
        headers = {}
        json_data = None

        response = self.parent._make_request(
            method="GET",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
