# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class NetworkingBfdDisable:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def networking_bfd_disable(
        self,
        remote: str,
        switch: Name,
    ) -> Any:
        """


        Args:
            remote: Address of the remote peer to disable a BFD session for.
            switch: Names must begin with a lower case ASCII letter, be composed exclusively of lowercase ASCII, uppercase ASCII, numbers, and '-', and may not end with a '-'. Names cannot be a UUID, but they may contain a UUID. They can be at most 63 characters long.

        Returns:
            Response data
        """
        path = f"/v1/system/networking/bfd-disable"
        params = None
        headers = None
        json_data = {
            "remote": remote if remote is not None else None,
            "switch": switch if switch is not None else None,
        }
        json_data = {k: v for k, v in json_data.items() if v is not None}

        response = self.parent._make_request(
            method="POST",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
