# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ...models.models import *

from .create_topic.create_topic import CreateTopic
from .update_topic.update_topic import UpdateTopic
from .clone_topic.clone_topic import CloneTopic
from .get_all_topics_for_owner_id.get_all_topics_for_owner_id import (
    GetAllTopicsForOwnerId,
)
from .delete_topic.delete_topic import DeleteTopic

if TYPE_CHECKING:
    from ..trieve_api import TrieveApi


class Topic:
    def __init__(self, parent: "TrieveApi"):
        """
        Topic chat endpoint. Think of topics as the storage system for gen-ai chat memory. Gen AI messages belong to topics.

        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.create_topic = CreateTopic(parent=parent).create_topic
        self.update_topic = UpdateTopic(parent=parent).update_topic
        self.clone_topic = CloneTopic(parent=parent).clone_topic
        self.get_all_topics_for_owner_id = GetAllTopicsForOwnerId(
            parent=parent
        ).get_all_topics_for_owner_id
        self.delete_topic = DeleteTopic(parent=parent).delete_topic
