# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ...models.models import *

from .create_setup_checkout_session.create_setup_checkout_session import (
    CreateSetupCheckoutSession,
)
from .get_all_invoices.get_all_invoices import GetAllInvoices
from .direct_to_payment_link.direct_to_payment_link import DirectToPaymentLink
from .get_all_plans.get_all_plans import GetAllPlans
from .cancel_subscription.cancel_subscription import CancelSubscription
from .update_subscription_plan.update_subscription_plan import UpdateSubscriptionPlan

if TYPE_CHECKING:
    from ..trieve_api import TrieveApi


class Stripe:
    def __init__(self, parent: "TrieveApi"):
        """
        Stripe endpoint. Used for the managed SaaS version of this app. Eventually this will become a micro-service. Reach out to the team using contact info found at `docs.trieve.ai` for more information.

        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.create_setup_checkout_session = CreateSetupCheckoutSession(
            parent=parent
        ).create_setup_checkout_session
        self.get_all_invoices = GetAllInvoices(parent=parent).get_all_invoices
        self.direct_to_payment_link = DirectToPaymentLink(
            parent=parent
        ).direct_to_payment_link
        self.get_all_plans = GetAllPlans(parent=parent).get_all_plans
        self.cancel_subscription = CancelSubscription(parent=parent).cancel_subscription
        self.update_subscription_plan = UpdateSubscriptionPlan(
            parent=parent
        ).update_subscription_plan
