# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class LocalIdpUserSetPassword:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def local_idp_user_set_password(
        self,
        user_id: str,
        silo: NameOrId,
        request_body: Optional[UserPassword] = None,
    ) -> Any:
        """
        Passwords can only be updated for users in Silos with identity mode `LocalOnly`.

        Args:
            user_id: The user's internal ID
            silo: Name or ID of the silo
            request_body: Request body

        Returns:
            Response data
        """
        path = f"/v1/system/identity-providers/local/users/{user_id}/set-password"
        params = {}
        headers = {}
        if silo is not None:
            params["silo"] = silo
        json_data = request_body.model_dump() if request_body else None

        response = self.parent._make_request(
            method="POST",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
