# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ...models.models import *

from .certificate_list.certificate_list import CertificateList
from .certificate_create.certificate_create import CertificateCreate
from .certificate_view.certificate_view import CertificateView
from .certificate_delete.certificate_delete import CertificateDelete
from .group_list.group_list import GroupList
from .group_view.group_view import GroupView
from .policy_view.policy_view import PolicyView
from .policy_update.policy_update import PolicyUpdate
from .user_list.user_list import UserList
from .utilization_view.utilization_view import UtilizationView

if TYPE_CHECKING:
    from ..oxide_region_api import OxideRegionAPI


class Silos:
    def __init__(self, parent: "OxideRegionAPI"):
        """
        Silos represent a logical partition of users and resources.

        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.certificate_list = CertificateList(parent=parent).certificate_list
        self.certificate_create = CertificateCreate(parent=parent).certificate_create
        self.certificate_view = CertificateView(parent=parent).certificate_view
        self.certificate_delete = CertificateDelete(parent=parent).certificate_delete
        self.group_list = GroupList(parent=parent).group_list
        self.group_view = GroupView(parent=parent).group_view
        self.policy_view = PolicyView(parent=parent).policy_view
        self.policy_update = PolicyUpdate(parent=parent).policy_update
        self.user_list = UserList(parent=parent).user_list
        self.utilization_view = UtilizationView(parent=parent).utilization_view
