# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ...models.models import *

from .role_list.role_list import RoleList
from .role_view.role_view import RoleView

if TYPE_CHECKING:
    from ..oxide_region_api import OxideRegionAPI


class Roles:
    def __init__(self, parent: "OxideRegionAPI"):
        """
        Roles are a component of Identity and Access Management (IAM) that allow a user or agent account access to additional permissions.

        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.role_list = RoleList(parent=parent).role_list
        self.role_view = RoleView(parent=parent).role_view
