# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ...models.models import *

from .physical_disk_list.physical_disk_list import PhysicalDiskList
from .physical_disk_view.physical_disk_view import PhysicalDiskView
from .rack_list.rack_list import RackList
from .rack_view.rack_view import RackView
from .sled_list.sled_list import SledList
from .sled_add.sled_add import SledAdd
from .sled_view.sled_view import SledView
from .sled_physical_disk_list.sled_physical_disk_list import SledPhysicalDiskList
from .sled_instance_list.sled_instance_list import SledInstanceList
from .sled_set_provision_policy.sled_set_provision_policy import SledSetProvisionPolicy
from .sled_list_uninitialized.sled_list_uninitialized import SledListUninitialized
from .networking_switch_port_list.networking_switch_port_list import (
    NetworkingSwitchPortList,
)
from .networking_switch_port_apply_settings.networking_switch_port_apply_settings import (
    NetworkingSwitchPortApplySettings,
)
from .networking_switch_port_clear_settings.networking_switch_port_clear_settings import (
    NetworkingSwitchPortClearSettings,
)
from .networking_switch_port_status.networking_switch_port_status import (
    NetworkingSwitchPortStatus,
)
from .switch_list.switch_list import SwitchList
from .switch_view.switch_view import SwitchView

if TYPE_CHECKING:
    from ..oxide_region_api import OxideRegionAPI


class SystemHardware:
    def __init__(self, parent: "OxideRegionAPI"):
        """
        These operations pertain to hardware inventory and management. Racks are the unit of expansion of an Oxide deployment. Racks are in turn composed of sleds, switches, power supplies, and a cabled backplane.

        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.physical_disk_list = PhysicalDiskList(parent=parent).physical_disk_list
        self.physical_disk_view = PhysicalDiskView(parent=parent).physical_disk_view
        self.rack_list = RackList(parent=parent).rack_list
        self.rack_view = RackView(parent=parent).rack_view
        self.sled_list = SledList(parent=parent).sled_list
        self.sled_add = SledAdd(parent=parent).sled_add
        self.sled_view = SledView(parent=parent).sled_view
        self.sled_physical_disk_list = SledPhysicalDiskList(
            parent=parent
        ).sled_physical_disk_list
        self.sled_instance_list = SledInstanceList(parent=parent).sled_instance_list
        self.sled_set_provision_policy = SledSetProvisionPolicy(
            parent=parent
        ).sled_set_provision_policy
        self.sled_list_uninitialized = SledListUninitialized(
            parent=parent
        ).sled_list_uninitialized
        self.networking_switch_port_list = NetworkingSwitchPortList(
            parent=parent
        ).networking_switch_port_list
        self.networking_switch_port_apply_settings = NetworkingSwitchPortApplySettings(
            parent=parent
        ).networking_switch_port_apply_settings
        self.networking_switch_port_clear_settings = NetworkingSwitchPortClearSettings(
            parent=parent
        ).networking_switch_port_clear_settings
        self.networking_switch_port_status = NetworkingSwitchPortStatus(
            parent=parent
        ).networking_switch_port_status
        self.switch_list = SwitchList(parent=parent).switch_list
        self.switch_view = SwitchView(parent=parent).switch_view
