# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...trieve_api import TrieveApi


class GetMessageById:
    def __init__(self, parent: "TrieveApi"):
        self.parent = parent

    def get_message_by_id(
        self,
        tr_dataset: str,
        message_id: str,
    ) -> Any:
        """
        Quickly get the full object for a given message. From the message, you can get the topic and all messages which exist on that topic.

        Args:
            tr_dataset: The dataset id or tracking_id to use for the request. We assume you intend to use an id if the value is a valid uuid.
            message_id: The ID of the message to get.

        Returns:
            Response data
        """
        path = f"/api/message/{message_id}"
        params = {}
        headers = {}
        if tr_dataset is not None:
            headers["TR-Dataset"] = tr_dataset
        json_data = None

        response = self.parent._make_request(
            method="GET",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
