# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ...models.models import *

from .get_metrics.get_metrics import GetMetrics

if TYPE_CHECKING:
    from ..trieve_api import TrieveApi


class Metrics:
    def __init__(self, parent: "TrieveApi"):
        """
        Metrics endpoint. Used to get information for monitoring

        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.get_metrics = GetMetrics(parent=parent).get_metrics
