# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ...models.models import *

from .image_list.image_list import ImageList
from .image_create.image_create import ImageCreate
from .image_view.image_view import ImageView
from .image_delete.image_delete import ImageDelete
from .image_demote.image_demote import ImageDemote
from .image_promote.image_promote import ImagePromote

if TYPE_CHECKING:
    from ..oxide_region_api import OxideRegionAPI


class Images:
    def __init__(self, parent: "OxideRegionAPI"):
        """
        Images are read-only virtual disks that may be used to boot virtual machines.

        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.image_list = ImageList(parent=parent).image_list
        self.image_create = ImageCreate(parent=parent).image_create
        self.image_view = ImageView(parent=parent).image_view
        self.image_delete = ImageDelete(parent=parent).image_delete
        self.image_demote = ImageDemote(parent=parent).image_demote
        self.image_promote = ImagePromote(parent=parent).image_promote
