# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...trieve_api import TrieveApi


class Login:
    def __init__(self, parent: "TrieveApi"):
        self.parent = parent

    def login(
        self,
        organization_id: Optional[str] = None,
        redirect_uri: Optional[str] = None,
        inv_code: Optional[str] = None,
    ) -> Any:
        """
        This will redirect you to the OAuth provider for authentication with email/pass, SSO, Google, Github, etc.

        Args:
            organization_id: ID of organization to authenticate into
            redirect_uri: URL to redirect to after successful login
            inv_code: Code sent via email as a result of successful call to send_invitation

        Returns:
            Response data
        """
        path = f"/api/auth"
        params = {}
        headers = {}
        if organization_id is not None:
            params["organization_id"] = organization_id
        if redirect_uri is not None:
            params["redirect_uri"] = redirect_uri
        if inv_code is not None:
            params["inv_code"] = inv_code
        json_data = None

        response = self.parent._make_request(
            method="GET",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
