# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...trieve_api import TrieveApi


class Logout:
    def __init__(self, parent: "TrieveApi"):
        self.parent = parent

    def logout(
        self,
    ) -> Any:
        """
        Invalidate your current auth credential stored typically stored in a cookie. This does not invalidate your API key.

        Returns:
            Response data
        """
        path = f"/api/auth"
        params = None
        headers = None
        json_data = None

        response = self.parent._make_request(
            method="DELETE",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
