# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class TimeseriesQuery:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def timeseries_query(
        self,
        project: NameOrId,
        query: str,
    ) -> Any:
        """
        Queries are written in OxQL. Project must be specified by name or ID in URL query parameter. The OxQL query will only return timeseries data from the specified project.

        Args:
            project: Name or ID of the project
            query: A timeseries query string, written in the Oximeter query language.

        Returns:
            Response data
        """
        path = f"/v1/timeseries/query"
        params = {}
        headers = {}
        if project is not None:
            params["project"] = project
        json_data = {
            "query": query if query is not None else None,
        }
        json_data = {k: v for k, v in json_data.items() if v is not None}

        response = self.parent._make_request(
            method="POST",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
