# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ...models.models import *

from .silo_identity_provider_list.silo_identity_provider_list import (
    SiloIdentityProviderList,
)
from .local_idp_user_create.local_idp_user_create import LocalIdpUserCreate
from .local_idp_user_delete.local_idp_user_delete import LocalIdpUserDelete
from .local_idp_user_set_password.local_idp_user_set_password import (
    LocalIdpUserSetPassword,
)
from .saml_identity_provider_create.saml_identity_provider_create import (
    SamlIdentityProviderCreate,
)
from .saml_identity_provider_view.saml_identity_provider_view import (
    SamlIdentityProviderView,
)
from .system_quotas_list.system_quotas_list import SystemQuotasList
from .silo_list.silo_list import SiloList
from .silo_create.silo_create import SiloCreate
from .silo_view.silo_view import SiloView
from .silo_delete.silo_delete import SiloDelete
from .silo_ip_pool_list.silo_ip_pool_list import SiloIpPoolList
from .silo_policy_view.silo_policy_view import SiloPolicyView
from .silo_policy_update.silo_policy_update import SiloPolicyUpdate
from .silo_quotas_view.silo_quotas_view import SiloQuotasView
from .silo_quotas_update.silo_quotas_update import SiloQuotasUpdate
from .silo_user_list.silo_user_list import SiloUserList
from .silo_user_view.silo_user_view import SiloUserView
from .user_builtin_list.user_builtin_list import UserBuiltinList
from .user_builtin_view.user_builtin_view import UserBuiltinView
from .silo_utilization_list.silo_utilization_list import SiloUtilizationList
from .silo_utilization_view.silo_utilization_view import SiloUtilizationView

if TYPE_CHECKING:
    from ..oxide_region_api import OxideRegionAPI


class SystemSilos:
    def __init__(self, parent: "OxideRegionAPI"):
        """
        Silos represent a logical partition of users and resources.

        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.silo_identity_provider_list = SiloIdentityProviderList(
            parent=parent
        ).silo_identity_provider_list
        self.local_idp_user_create = LocalIdpUserCreate(
            parent=parent
        ).local_idp_user_create
        self.local_idp_user_delete = LocalIdpUserDelete(
            parent=parent
        ).local_idp_user_delete
        self.local_idp_user_set_password = LocalIdpUserSetPassword(
            parent=parent
        ).local_idp_user_set_password
        self.saml_identity_provider_create = SamlIdentityProviderCreate(
            parent=parent
        ).saml_identity_provider_create
        self.saml_identity_provider_view = SamlIdentityProviderView(
            parent=parent
        ).saml_identity_provider_view
        self.system_quotas_list = SystemQuotasList(parent=parent).system_quotas_list
        self.silo_list = SiloList(parent=parent).silo_list
        self.silo_create = SiloCreate(parent=parent).silo_create
        self.silo_view = SiloView(parent=parent).silo_view
        self.silo_delete = SiloDelete(parent=parent).silo_delete
        self.silo_ip_pool_list = SiloIpPoolList(parent=parent).silo_ip_pool_list
        self.silo_policy_view = SiloPolicyView(parent=parent).silo_policy_view
        self.silo_policy_update = SiloPolicyUpdate(parent=parent).silo_policy_update
        self.silo_quotas_view = SiloQuotasView(parent=parent).silo_quotas_view
        self.silo_quotas_update = SiloQuotasUpdate(parent=parent).silo_quotas_update
        self.silo_user_list = SiloUserList(parent=parent).silo_user_list
        self.silo_user_view = SiloUserView(parent=parent).silo_user_view
        self.user_builtin_list = UserBuiltinList(parent=parent).user_builtin_list
        self.user_builtin_view = UserBuiltinView(parent=parent).user_builtin_view
        self.silo_utilization_list = SiloUtilizationList(
            parent=parent
        ).silo_utilization_list
        self.silo_utilization_view = SiloUtilizationView(
            parent=parent
        ).silo_utilization_view
