# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ...models.models import *

from .send_ctr_data.send_ctr_data import SendCtrData
from .send_event_data.send_event_data import SendEventData
from .get_all_events.get_all_events import GetAllEvents
from .get_ctr_analytics.get_ctr_analytics import GetCtrAnalytics
from .get_event_by_id.get_event_by_id import GetEventById
from .get_rag_analytics.get_rag_analytics import GetRagAnalytics
from .set_rag_query_rating.set_rag_query_rating import SetRagQueryRating
from .get_recommendation_analytics.get_recommendation_analytics import (
    GetRecommendationAnalytics,
)
from .get_search_analytics.get_search_analytics import GetSearchAnalytics
from .set_search_query_rating.set_search_query_rating import SetSearchQueryRating
from .get_cluster_analytics.get_cluster_analytics import GetClusterAnalytics
from .get_top_datasets.get_top_datasets import GetTopDatasets

if TYPE_CHECKING:
    from ..trieve_api import TrieveApi


class Analytics:
    def __init__(self, parent: "TrieveApi"):
        """
        Analytics endpoint. Used to get information for search and RAG analytics

        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.send_ctr_data = SendCtrData(parent=parent).send_ctr_data
        self.send_event_data = SendEventData(parent=parent).send_event_data
        self.get_all_events = GetAllEvents(parent=parent).get_all_events
        self.get_ctr_analytics = GetCtrAnalytics(parent=parent).get_ctr_analytics
        self.get_event_by_id = GetEventById(parent=parent).get_event_by_id
        self.get_rag_analytics = GetRagAnalytics(parent=parent).get_rag_analytics
        self.set_rag_query_rating = SetRagQueryRating(
            parent=parent
        ).set_rag_query_rating
        self.get_recommendation_analytics = GetRecommendationAnalytics(
            parent=parent
        ).get_recommendation_analytics
        self.get_search_analytics = GetSearchAnalytics(
            parent=parent
        ).get_search_analytics
        self.set_search_query_rating = SetSearchQueryRating(
            parent=parent
        ).set_search_query_rating
        self.get_cluster_analytics = GetClusterAnalytics(
            parent=parent
        ).get_cluster_analytics
        self.get_top_datasets = GetTopDatasets(parent=parent).get_top_datasets
