# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class InstanceNetworkInterfaceCreate:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def instance_network_interface_create(
        self,
        instance: NameOrId,
        description: str,
        name: Name,
        subnet_name: Name,
        vpc_name: Name,
        project: Optional[NameOrId] = None,
        ip: Optional[str] = None,
    ) -> Any:
        """


        Args:
            instance: Name or ID of the instance
            description: Create-time parameters for an `InstanceNetworkInterface`
            name: Names must begin with a lower case ASCII letter, be composed exclusively of lowercase ASCII, uppercase ASCII, numbers, and '-', and may not end with a '-'. Names cannot be a UUID, but they may contain a UUID. They can be at most 63 characters long.
            subnet_name: Names must begin with a lower case ASCII letter, be composed exclusively of lowercase ASCII, uppercase ASCII, numbers, and '-', and may not end with a '-'. Names cannot be a UUID, but they may contain a UUID. They can be at most 63 characters long.
            vpc_name: Names must begin with a lower case ASCII letter, be composed exclusively of lowercase ASCII, uppercase ASCII, numbers, and '-', and may not end with a '-'. Names cannot be a UUID, but they may contain a UUID. They can be at most 63 characters long.
            project: Name or ID of the project, only required if `instance` is provided as a `Name`
            ip: The IP address for the interface. One will be auto-assigned if not provided.

        Returns:
            Response data
        """
        path = f"/v1/network-interfaces"
        params = {}
        headers = {}
        if instance is not None:
            params["instance"] = instance
        if project is not None:
            params["project"] = project
        json_data = {
            "description": description if description is not None else None,
            "ip": ip if ip is not None else None,
            "name": name if name is not None else None,
            "subnet_name": subnet_name if subnet_name is not None else None,
            "vpc_name": vpc_name if vpc_name is not None else None,
        }
        json_data = {k: v for k, v in json_data.items() if v is not None}

        response = self.parent._make_request(
            method="POST",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
