# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class ProbeDelete:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def probe_delete(
        self,
        project: NameOrId,
        probe: NameOrId,
    ) -> Any:
        """


        Args:
            project: Name or ID of the project
            probe: Name or ID of the probe

        Returns:
            Response data
        """
        path = f"/experimental/v1/probes/{probe}"
        params = {}
        headers = {}
        if project is not None:
            params["project"] = project
        json_data = None

        response = self.parent._make_request(
            method="DELETE",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
