# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...trieve_api import TrieveApi


class GetAllEvents:
    def __init__(self, parent: "TrieveApi"):
        self.parent = parent

    def get_all_events(
        self,
        filter: Optional[EventAnalyticsFilter] = None,
        page: Optional[int] = None,
    ) -> Any:
        """
        This route allows you to view all user events.

        Args:
            filter: Filter to apply to the events when querying for them
            page: Page of results to return

        Returns:
            Response data
        """
        path = f"/api/analytics/events/all"
        params = None
        headers = None
        json_data = {
            "filter": filter if filter is not None else None,
            "page": page if page is not None else None,
        }
        json_data = {k: v for k, v in json_data.items() if v is not None}

        response = self.parent._make_request(
            method="POST",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
