# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class DiskMetricsList:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def disk_metrics_list(
        self,
        disk: NameOrId,
        metric: DiskMetricName,
        end_time: Optional[str] = None,
        limit: Optional[int] = None,
        order: Optional[PaginationOrder] = None,
        page_token: Optional[str] = None,
        start_time: Optional[str] = None,
        project: Optional[NameOrId] = None,
    ) -> Any:
        """


        Args:
            disk:
            metric:
            end_time: An exclusive end time of metrics.
            limit: Maximum number of items returned by a single call
            order: Query result order
            page_token: Token returned by previous call to retrieve the subsequent page
            start_time: An inclusive start time of metrics.
            project: Name or ID of the project

        Returns:
            Response data
        """
        path = f"/v1/disks/{disk}/metrics/{metric}"
        params = {}
        headers = {}
        if end_time is not None:
            params["end_time"] = end_time
        if limit is not None:
            params["limit"] = limit
        if order is not None:
            params["order"] = order
        if page_token is not None:
            params["page_token"] = page_token
        if start_time is not None:
            params["start_time"] = start_time
        if project is not None:
            params["project"] = project
        json_data = None

        response = self.parent._make_request(
            method="GET",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
