# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...trieve_api import TrieveApi


class GetMetrics:
    def __init__(self, parent: "TrieveApi"):
        self.parent = parent

    def get_metrics(
        self,
    ) -> Any:
        """
        This route allows you to view the number of items in each queue in the Prometheus format.

        Returns:
            Response data
        """
        path = f"/metrics"
        params = None
        headers = None
        json_data = None

        response = self.parent._make_request(
            method="POST",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
