# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...trieve_api import TrieveApi


class DeleteUserApiKey:
    def __init__(self, parent: "TrieveApi"):
        self.parent = parent

    def delete_user_api_key(
        self,
        api_key_id: str,
    ) -> Any:
        """
        Delete an api key for the auth'ed user.

        Args:
            api_key_id: The id of the api key to delete

        Returns:
            Response data
        """
        path = f"/api/user/api_key/{api_key_id}"
        params = {}
        headers = {}
        json_data = None

        response = self.parent._make_request(
            method="DELETE",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
