# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class DiskCreate:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def disk_create(
        self,
        project: NameOrId,
        description: str,
        disk_source: DiskSource,
        name: Name,
        size: ByteCount,
    ) -> Any:
        """


        Args:
            project: Name or ID of the project
            description: Create-time parameters for a `Disk`
            disk_source: Create a blank disk
            name: Names must begin with a lower case ASCII letter, be composed exclusively of lowercase ASCII, uppercase ASCII, numbers, and '-', and may not end with a '-'. Names cannot be a UUID, but they may contain a UUID. They can be at most 63 characters long.
            size: Byte count to express memory or storage capacity.

        Returns:
            Response data
        """
        path = f"/v1/disks"
        params = {}
        headers = {}
        if project is not None:
            params["project"] = project
        json_data = {
            "description": description if description is not None else None,
            "disk_source": disk_source if disk_source is not None else None,
            "name": name if name is not None else None,
            "size": size if size is not None else None,
        }
        json_data = {k: v for k, v in json_data.items() if v is not None}

        response = self.parent._make_request(
            method="POST",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
