# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class InternetGatewayDelete:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def internet_gateway_delete(
        self,
        gateway: NameOrId,
        cascade: Optional[bool] = None,
        project: Optional[NameOrId] = None,
        vpc: Optional[NameOrId] = None,
    ) -> Any:
        """


        Args:
            gateway: Name or ID of the gateway
            cascade: Also delete routes targeting this gateway.
            project: Name or ID of the project, only required if `vpc` is provided as a `Name`
            vpc: Name or ID of the VPC

        Returns:
            Response data
        """
        path = f"/v1/internet-gateways/{gateway}"
        params = {}
        headers = {}
        if cascade is not None:
            params["cascade"] = cascade
        if project is not None:
            params["project"] = project
        if vpc is not None:
            params["vpc"] = vpc
        json_data = None

        response = self.parent._make_request(
            method="DELETE",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
