# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class SupportBundleDownload:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def support_bundle_download(
        self,
        support_bundle: str,
    ) -> Any:
        """


        Args:
            support_bundle: ID of the support bundle

        Returns:
            Response data
        """
        path = f"/experimental/v1/system/support-bundles/{support_bundle}/download"
        params = {}
        headers = {}
        json_data = None

        response = self.parent._make_request(
            method="GET",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
