# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class IpPoolDelete:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def ip_pool_delete(
        self,
        pool: NameOrId,
    ) -> Any:
        """


        Args:
            pool: Name or ID of the IP pool

        Returns:
            Response data
        """
        path = f"/v1/system/ip-pools/{pool}"
        params = {}
        headers = {}
        json_data = None

        response = self.parent._make_request(
            method="DELETE",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
