# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class VpcRouterRouteCreate:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def vpc_router_route_create(
        self,
        router: NameOrId,
        description: str,
        destination: RouteDestination,
        name: Name,
        target: RouteTarget,
        project: Optional[NameOrId] = None,
        vpc: Optional[NameOrId] = None,
    ) -> Any:
        """


        Args:
            router: Name or ID of the router
            description: Create-time parameters for a `RouterRoute`
            destination: Route applies to traffic destined for the specified IP address
            name: Names must begin with a lower case ASCII letter, be composed exclusively of lowercase ASCII, uppercase ASCII, numbers, and '-', and may not end with a '-'. Names cannot be a UUID, but they may contain a UUID. They can be at most 63 characters long.
            target: Forward traffic to a particular IP address.
            project: Name or ID of the project, only required if `vpc` is provided as a `Name`
            vpc: Name or ID of the VPC, only required if `router` is provided as a `Name`

        Returns:
            Response data
        """
        path = f"/v1/vpc-router-routes"
        params = {}
        headers = {}
        if project is not None:
            params["project"] = project
        if router is not None:
            params["router"] = router
        if vpc is not None:
            params["vpc"] = vpc
        json_data = {
            "description": description if description is not None else None,
            "destination": destination if destination is not None else None,
            "name": name if name is not None else None,
            "target": target if target is not None else None,
        }
        json_data = {k: v for k, v in json_data.items() if v is not None}

        response = self.parent._make_request(
            method="POST",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
