# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...trieve_api import TrieveApi


class CountGroupChunks:
    def __init__(self, parent: "TrieveApi"):
        self.parent = parent

    def count_group_chunks(
        self,
        tr_dataset: str,
        group_id: Optional[str] = None,
        group_tracking_id: Optional[str] = None,
    ) -> Any:
        """
        Route to get the number of chunks that is in a group

        Args:
            tr_dataset: The dataset id or tracking_id to use for the request. We assume you intend to use an id if the value is a valid uuid.
            group_id: The Id of the group to get the count for, is not required if group_tracking_id is provided.
            group_tracking_id: The tracking id of the group to get the count for, is not required if group_id is provided.

        Returns:
            Response data
        """
        path = f"/api/chunk_group/count"
        params = {}
        headers = {}
        if tr_dataset is not None:
            headers["TR-Dataset"] = tr_dataset
        json_data = {
            "group_id": group_id if group_id is not None else None,
            "group_tracking_id": (
                group_tracking_id if group_tracking_id is not None else None
            ),
        }
        json_data = {k: v for k, v in json_data.items() if v is not None}

        response = self.parent._make_request(
            method="POST",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
