# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class DeviceAuthRequest:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def device_auth_request(
        self,
        request_body: Optional[any] = None,
    ) -> Any:
        """
        This endpoint is designed to be accessed from an *unauthenticated* API client. It generates and records a `device_code` and `user_code` which must be verified and confirmed prior to a token being granted.

        Args:
            request_body: Request body

        Returns:
            Response data
        """
        path = f"/device/auth"
        params = None
        headers = None
        json_data = request_body.model_dump() if request_body else None

        response = self.parent._make_request(
            method="POST",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
