# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...trieve_api import TrieveApi


class GetGroupsForChunks:
    def __init__(self, parent: "TrieveApi"):
        self.parent = parent

    def get_groups_for_chunks(
        self,
        tr_dataset: str,
        chunk_ids: Optional[List[str]] = None,
        chunk_tracking_ids: Optional[List[str]] = None,
    ) -> Any:
        """
        Route to get the groups that a chunk is in.

        Args:
            tr_dataset: The dataset id or tracking_id to use for the request. We assume you intend to use an id if the value is a valid uuid.
            chunk_ids: No description provided
            chunk_tracking_ids: No description provided

        Returns:
            Response data
        """
        path = f"/api/chunk_group/chunks"
        params = {}
        headers = {}
        if tr_dataset is not None:
            headers["TR-Dataset"] = tr_dataset
        json_data = {
            "chunk_ids": chunk_ids if chunk_ids is not None else None,
            "chunk_tracking_ids": (
                chunk_tracking_ids if chunk_tracking_ids is not None else None
            ),
        }
        json_data = {k: v for k, v in json_data.items() if v is not None}

        response = self.parent._make_request(
            method="POST",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
