# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class ImageDemote:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def image_demote(
        self,
        image: NameOrId,
        project: NameOrId,
    ) -> Any:
        """
        Demote silo image to be visible only to a specified project

        Args:
            image: Name or ID of the image
            project: Name or ID of the project

        Returns:
            Response data
        """
        path = f"/v1/images/{image}/demote"
        params = {}
        headers = {}
        if project is not None:
            params["project"] = project
        json_data = None

        response = self.parent._make_request(
            method="POST",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
