# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ...models.models import *

from .instance_list.instance_list import InstanceList
from .instance_create.instance_create import InstanceCreate
from .instance_view.instance_view import InstanceView
from .instance_update.instance_update import InstanceUpdate
from .instance_delete.instance_delete import InstanceDelete
from .instance_disk_list.instance_disk_list import InstanceDiskList
from .instance_disk_attach.instance_disk_attach import InstanceDiskAttach
from .instance_disk_detach.instance_disk_detach import InstanceDiskDetach
from .instance_external_ip_list.instance_external_ip_list import InstanceExternalIpList
from .instance_ephemeral_ip_attach.instance_ephemeral_ip_attach import (
    InstanceEphemeralIpAttach,
)
from .instance_ephemeral_ip_detach.instance_ephemeral_ip_detach import (
    InstanceEphemeralIpDetach,
)
from .instance_reboot.instance_reboot import InstanceReboot
from .instance_serial_console.instance_serial_console import InstanceSerialConsole
from .instance_serial_console_stream.instance_serial_console_stream import (
    InstanceSerialConsoleStream,
)
from .instance_ssh_public_key_list.instance_ssh_public_key_list import (
    InstanceSshPublicKeyList,
)
from .instance_start.instance_start import InstanceStart
from .instance_stop.instance_stop import InstanceStop
from .instance_network_interface_list.instance_network_interface_list import (
    InstanceNetworkInterfaceList,
)
from .instance_network_interface_create.instance_network_interface_create import (
    InstanceNetworkInterfaceCreate,
)
from .instance_network_interface_view.instance_network_interface_view import (
    InstanceNetworkInterfaceView,
)
from .instance_network_interface_update.instance_network_interface_update import (
    InstanceNetworkInterfaceUpdate,
)
from .instance_network_interface_delete.instance_network_interface_delete import (
    InstanceNetworkInterfaceDelete,
)

if TYPE_CHECKING:
    from ..oxide_region_api import OxideRegionAPI


class Instances:
    def __init__(self, parent: "OxideRegionAPI"):
        """
        Virtual machine instances are the basic unit of computation. These operations are used for provisioning, controlling, and destroying instances.

        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.instance_list = InstanceList(parent=parent).instance_list
        self.instance_create = InstanceCreate(parent=parent).instance_create
        self.instance_view = InstanceView(parent=parent).instance_view
        self.instance_update = InstanceUpdate(parent=parent).instance_update
        self.instance_delete = InstanceDelete(parent=parent).instance_delete
        self.instance_disk_list = InstanceDiskList(parent=parent).instance_disk_list
        self.instance_disk_attach = InstanceDiskAttach(
            parent=parent
        ).instance_disk_attach
        self.instance_disk_detach = InstanceDiskDetach(
            parent=parent
        ).instance_disk_detach
        self.instance_external_ip_list = InstanceExternalIpList(
            parent=parent
        ).instance_external_ip_list
        self.instance_ephemeral_ip_attach = InstanceEphemeralIpAttach(
            parent=parent
        ).instance_ephemeral_ip_attach
        self.instance_ephemeral_ip_detach = InstanceEphemeralIpDetach(
            parent=parent
        ).instance_ephemeral_ip_detach
        self.instance_reboot = InstanceReboot(parent=parent).instance_reboot
        self.instance_serial_console = InstanceSerialConsole(
            parent=parent
        ).instance_serial_console
        self.instance_serial_console_stream = InstanceSerialConsoleStream(
            parent=parent
        ).instance_serial_console_stream
        self.instance_ssh_public_key_list = InstanceSshPublicKeyList(
            parent=parent
        ).instance_ssh_public_key_list
        self.instance_start = InstanceStart(parent=parent).instance_start
        self.instance_stop = InstanceStop(parent=parent).instance_stop
        self.instance_network_interface_list = InstanceNetworkInterfaceList(
            parent=parent
        ).instance_network_interface_list
        self.instance_network_interface_create = InstanceNetworkInterfaceCreate(
            parent=parent
        ).instance_network_interface_create
        self.instance_network_interface_view = InstanceNetworkInterfaceView(
            parent=parent
        ).instance_network_interface_view
        self.instance_network_interface_update = InstanceNetworkInterfaceUpdate(
            parent=parent
        ).instance_network_interface_update
        self.instance_network_interface_delete = InstanceNetworkInterfaceDelete(
            parent=parent
        ).instance_network_interface_delete
