# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...trieve_api import TrieveApi


class CreateOrganization:
    def __init__(self, parent: "TrieveApi"):
        self.parent = parent

    def create_organization(
        self,
        name: str,
    ) -> Any:
        """
        Create a new organization. The auth'ed user who creates the organization will be the default owner of the organization.

        Args:
            name: The arbitrary name which will be used to identify the organization. This name must be unique.

        Returns:
            Response data
        """
        path = f"/api/organization"
        params = None
        headers = None
        json_data = {
            "name": name if name is not None else None,
        }
        json_data = {k: v for k, v in json_data.items() if v is not None}

        response = self.parent._make_request(
            method="POST",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
