# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ...models.models import *

from .health_check.health_check import HealthCheck

if TYPE_CHECKING:
    from ..trieve_api import TrieveApi


class Health:
    def __init__(self, parent: "TrieveApi"):
        """
        Health check endpoint. Used to check if the server is up and running.

        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.health_check = HealthCheck(parent=parent).health_check
