# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ...models.models import *

from .update_user.update_user import UpdateUser
from .get_user_api_keys.get_user_api_keys import GetUserApiKeys
from .delete_user_api_key.delete_user_api_key import DeleteUserApiKey

if TYPE_CHECKING:
    from ..trieve_api import TrieveApi


class User:
    def __init__(self, parent: "TrieveApi"):
        """
        User endpoint. Enables you to modify user roles and information.

        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.update_user = UpdateUser(parent=parent).update_user
        self.get_user_api_keys = GetUserApiKeys(parent=parent).get_user_api_keys
        self.delete_user_api_key = DeleteUserApiKey(parent=parent).delete_user_api_key
