# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ...models.models import *

from .system_policy_view.system_policy_view import SystemPolicyView
from .system_policy_update.system_policy_update import SystemPolicyUpdate

if TYPE_CHECKING:
    from ..oxide_region_api import OxideRegionAPI


class Policy:
    def __init__(self, parent: "OxideRegionAPI"):
        """
        System-wide IAM policy

        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.system_policy_view = SystemPolicyView(parent=parent).system_policy_view
        self.system_policy_update = SystemPolicyUpdate(
            parent=parent
        ).system_policy_update
