# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...trieve_api import TrieveApi


class GetFileHandler:
    def __init__(self, parent: "TrieveApi"):
        self.parent = parent

    def get_file_handler(
        self,
        tr_dataset: str,
        file_id: str,
        content_type: Optional[str] = None,
    ) -> Any:
        """
        Get a signed s3 url corresponding to the file_id requested such that you can download the file.

        Args:
            tr_dataset: The dataset id or tracking_id to use for the request. We assume you intend to use an id if the value is a valid uuid.
            file_id: The id of the file to fetch
            content_type: Optional field to override the presigned url's Content-Type header

        Returns:
            Response data
        """
        path = f"/api/file/{file_id}"
        params = {}
        headers = {}
        if tr_dataset is not None:
            headers["TR-Dataset"] = tr_dataset
        if content_type is not None:
            params["content_type"] = content_type
        json_data = None

        response = self.parent._make_request(
            method="GET",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
