# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...trieve_api import TrieveApi


class GetUserApiKeys:
    def __init__(self, parent: "TrieveApi"):
        self.parent = parent

    def get_user_api_keys(
        self,
    ) -> Any:
        """
        Get the api keys which belong to the auth'ed user. The actual api key values are not returned, only the ids, names, and creation dates.

        Returns:
            Response data
        """
        path = f"/api/user/api_key"
        params = None
        headers = None
        json_data = None

        response = self.parent._make_request(
            method="GET",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
