# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class NetworkingAllowListUpdate:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def networking_allow_list_update(
        self,
        allowed_ips: AllowedSourceIps,
    ) -> Any:
        """


        Args:
            allowed_ips: Allow traffic from any external IP address.

        Returns:
            Response data
        """
        path = f"/v1/system/networking/allow-list"
        params = None
        headers = None
        json_data = {
            "allowed_ips": allowed_ips if allowed_ips is not None else None,
        }
        json_data = {k: v for k, v in json_data.items() if v is not None}

        response = self.parent._make_request(
            method="PUT",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
