# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...trieve_api import TrieveApi


class GetEventById:
    def __init__(self, parent: "TrieveApi"):
        self.parent = parent

    def get_event_by_id(
        self,
        tr_dataset: str,
        event_id: str,
    ) -> Any:
        """
        This route allows you to view an user event by its ID. You can pass in any type of event and get the details for that event.

        Args:
            tr_dataset: The dataset id or tracking_id to use for the request. We assume you intend to use an id if the value is a valid uuid.
            event_id: The event id to use for the request

        Returns:
            Response data
        """
        path = f"/api/analytics/events/{event_id}"
        params = {}
        headers = {}
        if tr_dataset is not None:
            headers["TR-Dataset"] = tr_dataset
        json_data = None

        response = self.parent._make_request(
            method="GET",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
