# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...trieve_api import TrieveApi


class GetAllTopicsForOwnerId:
    def __init__(self, parent: "TrieveApi"):
        self.parent = parent

    def get_all_topics_for_owner_id(
        self,
        owner_id: str,
        tr_dataset: str,
    ) -> Any:
        """
        Get all topics belonging to an arbitary owner_id. This is useful for managing message history and chat sessions. It is common to use a browser fingerprint or your user's id as the owner_id. Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.

        Args:
            owner_id: The owner_id to get topics of; A common approach is to use a browser fingerprint or your user's id
            tr_dataset: The dataset id or tracking_id to use for the request. We assume you intend to use an id if the value is a valid uuid.

        Returns:
            Response data
        """
        path = f"/api/topic/owner/{owner_id}"
        params = {}
        headers = {}
        if tr_dataset is not None:
            headers["TR-Dataset"] = tr_dataset
        json_data = None

        response = self.parent._make_request(
            method="GET",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
