# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...trieve_api import TrieveApi


class GetInvitations:
    def __init__(self, parent: "TrieveApi"):
        self.parent = parent

    def get_invitations(
        self,
        tr_organization: str,
        organization_id: str,
    ) -> Any:
        """
        Get all invitations for the organization. Auth'ed user or api key must have an admin or owner role for the specified dataset's organization.

        Args:
            tr_organization: The organization id to use for the request
            organization_id: The organization id to get invitations for

        Returns:
            Response data
        """
        path = f"/api/invitations/{organization_id}"
        params = {}
        headers = {}
        if tr_organization is not None:
            headers["TR-Organization"] = tr_organization
        json_data = None

        response = self.parent._make_request(
            method="GET",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
