# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class NetworkingSwitchPortLldpNeighbors:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def networking_switch_port_lldp_neighbors(
        self,
        port: Name,
        rack_id: str,
        switch_location: Name,
        limit: Optional[int] = None,
        page_token: Optional[str] = None,
        sort_by: Optional[IdSortMode] = None,
    ) -> Any:
        """


        Args:
            port: A name to use when selecting switch ports.
            rack_id: A rack id to use when selecting switch ports.
            switch_location: A switch location to use when selecting switch ports.
            limit: Maximum number of items returned by a single call
            page_token: Token returned by previous call to retrieve the subsequent page
            sort_by:

        Returns:
            Response data
        """
        path = f"/v1/system/hardware/rack-switch-port/{rack_id}/{switch_location}/{port}/lldp/neighbors"
        params = {}
        headers = {}
        if limit is not None:
            params["limit"] = limit
        if page_token is not None:
            params["page_token"] = page_token
        if sort_by is not None:
            params["sort_by"] = sort_by
        json_data = None

        response = self.parent._make_request(
            method="GET",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
