# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ...models.models import *

from .ping.ping import Ping

if TYPE_CHECKING:
    from ..oxide_region_api import OxideRegionAPI


class SystemStatus:
    def __init__(self, parent: "OxideRegionAPI"):
        """
        Endpoints related to system health

        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.ping = Ping(parent=parent).ping
