# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ...models.models import *

from .create_organization.create_organization import CreateOrganization
from .update_organization.update_organization import UpdateOrganization
from .get_organization_api_keys.get_organization_api_keys import GetOrganizationApiKeys
from .create_organization_api_key.create_organization_api_key import (
    CreateOrganizationApiKey,
)
from .delete_organization_api_key.delete_organization_api_key import (
    DeleteOrganizationApiKey,
)
from .update_all_org_dataset_configs.update_all_org_dataset_configs import (
    UpdateAllOrgDatasetConfigs,
)
from .get_organization_usage.get_organization_usage import GetOrganizationUsage
from .get_organization_users.get_organization_users import GetOrganizationUsers
from .get_organization.get_organization import GetOrganization
from .delete_organization.delete_organization import DeleteOrganization

if TYPE_CHECKING:
    from ..trieve_api import TrieveApi


class Organization:
    def __init__(self, parent: "TrieveApi"):
        """
        Organization endpoint. Enables you to modify organization roles and information.

        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.create_organization = CreateOrganization(parent=parent).create_organization
        self.update_organization = UpdateOrganization(parent=parent).update_organization
        self.get_organization_api_keys = GetOrganizationApiKeys(
            parent=parent
        ).get_organization_api_keys
        self.create_organization_api_key = CreateOrganizationApiKey(
            parent=parent
        ).create_organization_api_key
        self.delete_organization_api_key = DeleteOrganizationApiKey(
            parent=parent
        ).delete_organization_api_key
        self.update_all_org_dataset_configs = UpdateAllOrgDatasetConfigs(
            parent=parent
        ).update_all_org_dataset_configs
        self.get_organization_usage = GetOrganizationUsage(
            parent=parent
        ).get_organization_usage
        self.get_organization_users = GetOrganizationUsers(
            parent=parent
        ).get_organization_users
        self.get_organization = GetOrganization(parent=parent).get_organization
        self.delete_organization = DeleteOrganization(parent=parent).delete_organization
