# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ...models.models import *

from .create_chunk_group.create_chunk_group import CreateChunkGroup
from .update_chunk_group.update_chunk_group import UpdateChunkGroup
from .add_chunk_to_group.add_chunk_to_group import AddChunkToGroup
from .remove_chunk_from_group.remove_chunk_from_group import RemoveChunkFromGroup
from .get_groups_for_chunks.get_groups_for_chunks import GetGroupsForChunks
from .count_group_chunks.count_group_chunks import CountGroupChunks
from .search_over_groups.search_over_groups import SearchOverGroups
from .get_recommended_groups.get_recommended_groups import GetRecommendedGroups
from .search_within_group.search_within_group import SearchWithinGroup
from .get_chunks_in_group_by_tracking_id.get_chunks_in_group_by_tracking_id import (
    GetChunksInGroupByTrackingId,
)
from .get_group_by_tracking_id.get_group_by_tracking_id import GetGroupByTrackingId
from .add_chunk_to_group_by_tracking_id.add_chunk_to_group_by_tracking_id import (
    AddChunkToGroupByTrackingId,
)
from .delete_group_by_tracking_id.delete_group_by_tracking_id import (
    DeleteGroupByTrackingId,
)
from .get_chunk_group.get_chunk_group import GetChunkGroup
from .delete_chunk_group.delete_chunk_group import DeleteChunkGroup
from .get_chunks_in_group.get_chunks_in_group import GetChunksInGroup
from .get_groups_for_dataset.get_groups_for_dataset import GetGroupsForDataset

if TYPE_CHECKING:
    from ..trieve_api import TrieveApi


class ChunkGroup:
    def __init__(self, parent: "TrieveApi"):
        """
        Chunk groups endpoint. Think of a chunk_group as a bookmark folder within the dataset.

        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.create_chunk_group = CreateChunkGroup(parent=parent).create_chunk_group
        self.update_chunk_group = UpdateChunkGroup(parent=parent).update_chunk_group
        self.add_chunk_to_group = AddChunkToGroup(parent=parent).add_chunk_to_group
        self.remove_chunk_from_group = RemoveChunkFromGroup(
            parent=parent
        ).remove_chunk_from_group
        self.get_groups_for_chunks = GetGroupsForChunks(
            parent=parent
        ).get_groups_for_chunks
        self.count_group_chunks = CountGroupChunks(parent=parent).count_group_chunks
        self.search_over_groups = SearchOverGroups(parent=parent).search_over_groups
        self.get_recommended_groups = GetRecommendedGroups(
            parent=parent
        ).get_recommended_groups
        self.search_within_group = SearchWithinGroup(parent=parent).search_within_group
        self.get_chunks_in_group_by_tracking_id = GetChunksInGroupByTrackingId(
            parent=parent
        ).get_chunks_in_group_by_tracking_id
        self.get_group_by_tracking_id = GetGroupByTrackingId(
            parent=parent
        ).get_group_by_tracking_id
        self.add_chunk_to_group_by_tracking_id = AddChunkToGroupByTrackingId(
            parent=parent
        ).add_chunk_to_group_by_tracking_id
        self.delete_group_by_tracking_id = DeleteGroupByTrackingId(
            parent=parent
        ).delete_group_by_tracking_id
        self.get_chunk_group = GetChunkGroup(parent=parent).get_chunk_group
        self.delete_chunk_group = DeleteChunkGroup(parent=parent).delete_chunk_group
        self.get_chunks_in_group = GetChunksInGroup(parent=parent).get_chunks_in_group
        self.get_groups_for_dataset = GetGroupsForDataset(
            parent=parent
        ).get_groups_for_dataset
