# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class PhysicalDiskView:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def physical_disk_view(
        self,
        disk_id: str,
    ) -> Any:
        """


        Args:
            disk_id: ID of the physical disk

        Returns:
            Response data
        """
        path = f"/v1/system/hardware/disks/{disk_id}"
        params = {}
        headers = {}
        json_data = None

        response = self.parent._make_request(
            method="GET",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
