# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class VpcRouterRouteView:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def vpc_router_route_view(
        self,
        route: NameOrId,
        router: NameOrId,
        project: Optional[NameOrId] = None,
        vpc: Optional[NameOrId] = None,
    ) -> Any:
        """


        Args:
            route: Name or ID of the route
            router: Name or ID of the router
            project: Name or ID of the project, only required if `vpc` is provided as a `Name`
            vpc: Name or ID of the VPC, only required if `router` is provided as a `Name`

        Returns:
            Response data
        """
        path = f"/v1/vpc-router-routes/{route}"
        params = {}
        headers = {}
        if project is not None:
            params["project"] = project
        if router is not None:
            params["router"] = router
        if vpc is not None:
            params["vpc"] = vpc
        json_data = None

        response = self.parent._make_request(
            method="GET",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
