# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class CertificateView:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def certificate_view(
        self,
        certificate: NameOrId,
    ) -> Any:
        """
        Returns the details of a specific certificate

        Args:
            certificate: Name or ID of the certificate

        Returns:
            Response data
        """
        path = f"/v1/certificates/{certificate}"
        params = {}
        headers = {}
        json_data = None

        response = self.parent._make_request(
            method="GET",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
