# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ...models.models import *

from .networking_switch_port_lldp_neighbors.networking_switch_port_lldp_neighbors import (
    NetworkingSwitchPortLldpNeighbors,
)
from .networking_switch_port_lldp_config_view.networking_switch_port_lldp_config_view import (
    NetworkingSwitchPortLldpConfigView,
)
from .networking_switch_port_lldp_config_update.networking_switch_port_lldp_config_update import (
    NetworkingSwitchPortLldpConfigUpdate,
)
from .networking_address_lot_list.networking_address_lot_list import (
    NetworkingAddressLotList,
)
from .networking_address_lot_create.networking_address_lot_create import (
    NetworkingAddressLotCreate,
)
from .networking_address_lot_delete.networking_address_lot_delete import (
    NetworkingAddressLotDelete,
)
from .networking_address_lot_block_list.networking_address_lot_block_list import (
    NetworkingAddressLotBlockList,
)
from .networking_allow_list_view.networking_allow_list_view import (
    NetworkingAllowListView,
)
from .networking_allow_list_update.networking_allow_list_update import (
    NetworkingAllowListUpdate,
)
from .networking_bfd_disable.networking_bfd_disable import NetworkingBfdDisable
from .networking_bfd_enable.networking_bfd_enable import NetworkingBfdEnable
from .networking_bfd_status.networking_bfd_status import NetworkingBfdStatus
from .networking_bgp_config_list.networking_bgp_config_list import (
    NetworkingBgpConfigList,
)
from .networking_bgp_config_create.networking_bgp_config_create import (
    NetworkingBgpConfigCreate,
)
from .networking_bgp_config_delete.networking_bgp_config_delete import (
    NetworkingBgpConfigDelete,
)
from .networking_bgp_announce_set_list.networking_bgp_announce_set_list import (
    NetworkingBgpAnnounceSetList,
)
from .networking_bgp_announce_set_update.networking_bgp_announce_set_update import (
    NetworkingBgpAnnounceSetUpdate,
)
from .networking_bgp_announce_set_delete.networking_bgp_announce_set_delete import (
    NetworkingBgpAnnounceSetDelete,
)
from .networking_bgp_announcement_list.networking_bgp_announcement_list import (
    NetworkingBgpAnnouncementList,
)
from .networking_bgp_exported.networking_bgp_exported import NetworkingBgpExported
from .networking_bgp_message_history.networking_bgp_message_history import (
    NetworkingBgpMessageHistory,
)
from .networking_bgp_imported_routes_ipv4.networking_bgp_imported_routes_ipv4 import (
    NetworkingBgpImportedRoutesIpv4,
)
from .networking_bgp_status.networking_bgp_status import NetworkingBgpStatus
from .networking_loopback_address_list.networking_loopback_address_list import (
    NetworkingLoopbackAddressList,
)
from .networking_loopback_address_create.networking_loopback_address_create import (
    NetworkingLoopbackAddressCreate,
)
from .networking_loopback_address_delete.networking_loopback_address_delete import (
    NetworkingLoopbackAddressDelete,
)
from .networking_switch_port_settings_list.networking_switch_port_settings_list import (
    NetworkingSwitchPortSettingsList,
)
from .networking_switch_port_settings_create.networking_switch_port_settings_create import (
    NetworkingSwitchPortSettingsCreate,
)
from .networking_switch_port_settings_delete.networking_switch_port_settings_delete import (
    NetworkingSwitchPortSettingsDelete,
)
from .networking_switch_port_settings_view.networking_switch_port_settings_view import (
    NetworkingSwitchPortSettingsView,
)

if TYPE_CHECKING:
    from ..oxide_region_api import OxideRegionAPI


class SystemNetworking:
    def __init__(self, parent: "OxideRegionAPI"):
        """
        This provides rack-level network configuration.

        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.networking_switch_port_lldp_neighbors = NetworkingSwitchPortLldpNeighbors(
            parent=parent
        ).networking_switch_port_lldp_neighbors
        self.networking_switch_port_lldp_config_view = (
            NetworkingSwitchPortLldpConfigView(
                parent=parent
            ).networking_switch_port_lldp_config_view
        )
        self.networking_switch_port_lldp_config_update = (
            NetworkingSwitchPortLldpConfigUpdate(
                parent=parent
            ).networking_switch_port_lldp_config_update
        )
        self.networking_address_lot_list = NetworkingAddressLotList(
            parent=parent
        ).networking_address_lot_list
        self.networking_address_lot_create = NetworkingAddressLotCreate(
            parent=parent
        ).networking_address_lot_create
        self.networking_address_lot_delete = NetworkingAddressLotDelete(
            parent=parent
        ).networking_address_lot_delete
        self.networking_address_lot_block_list = NetworkingAddressLotBlockList(
            parent=parent
        ).networking_address_lot_block_list
        self.networking_allow_list_view = NetworkingAllowListView(
            parent=parent
        ).networking_allow_list_view
        self.networking_allow_list_update = NetworkingAllowListUpdate(
            parent=parent
        ).networking_allow_list_update
        self.networking_bfd_disable = NetworkingBfdDisable(
            parent=parent
        ).networking_bfd_disable
        self.networking_bfd_enable = NetworkingBfdEnable(
            parent=parent
        ).networking_bfd_enable
        self.networking_bfd_status = NetworkingBfdStatus(
            parent=parent
        ).networking_bfd_status
        self.networking_bgp_config_list = NetworkingBgpConfigList(
            parent=parent
        ).networking_bgp_config_list
        self.networking_bgp_config_create = NetworkingBgpConfigCreate(
            parent=parent
        ).networking_bgp_config_create
        self.networking_bgp_config_delete = NetworkingBgpConfigDelete(
            parent=parent
        ).networking_bgp_config_delete
        self.networking_bgp_announce_set_list = NetworkingBgpAnnounceSetList(
            parent=parent
        ).networking_bgp_announce_set_list
        self.networking_bgp_announce_set_update = NetworkingBgpAnnounceSetUpdate(
            parent=parent
        ).networking_bgp_announce_set_update
        self.networking_bgp_announce_set_delete = NetworkingBgpAnnounceSetDelete(
            parent=parent
        ).networking_bgp_announce_set_delete
        self.networking_bgp_announcement_list = NetworkingBgpAnnouncementList(
            parent=parent
        ).networking_bgp_announcement_list
        self.networking_bgp_exported = NetworkingBgpExported(
            parent=parent
        ).networking_bgp_exported
        self.networking_bgp_message_history = NetworkingBgpMessageHistory(
            parent=parent
        ).networking_bgp_message_history
        self.networking_bgp_imported_routes_ipv4 = NetworkingBgpImportedRoutesIpv4(
            parent=parent
        ).networking_bgp_imported_routes_ipv4
        self.networking_bgp_status = NetworkingBgpStatus(
            parent=parent
        ).networking_bgp_status
        self.networking_loopback_address_list = NetworkingLoopbackAddressList(
            parent=parent
        ).networking_loopback_address_list
        self.networking_loopback_address_create = NetworkingLoopbackAddressCreate(
            parent=parent
        ).networking_loopback_address_create
        self.networking_loopback_address_delete = NetworkingLoopbackAddressDelete(
            parent=parent
        ).networking_loopback_address_delete
        self.networking_switch_port_settings_list = NetworkingSwitchPortSettingsList(
            parent=parent
        ).networking_switch_port_settings_list
        self.networking_switch_port_settings_create = (
            NetworkingSwitchPortSettingsCreate(
                parent=parent
            ).networking_switch_port_settings_create
        )
        self.networking_switch_port_settings_delete = (
            NetworkingSwitchPortSettingsDelete(
                parent=parent
            ).networking_switch_port_settings_delete
        )
        self.networking_switch_port_settings_view = NetworkingSwitchPortSettingsView(
            parent=parent
        ).networking_switch_port_settings_view
