# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ...models.models import *

from .silo_metric.silo_metric import SiloMetric

if TYPE_CHECKING:
    from ..oxide_region_api import OxideRegionAPI


class Metrics:
    def __init__(self, parent: "OxideRegionAPI"):
        """
        Silo-scoped metrics

        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.silo_metric = SiloMetric(parent=parent).silo_metric
