# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class SiloQuotasUpdate:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def silo_quotas_update(
        self,
        silo: NameOrId,
        cpus: Optional[int] = None,
        memory: Optional[ByteCount] = None,
        storage: Optional[ByteCount] = None,
    ) -> Any:
        """
        If a quota value is not specified, it will remain unchanged.

        Args:
            silo: Name or ID of the silo
            cpus: The amount of virtual CPUs available for running instances in the Silo
            memory: Byte count to express memory or storage capacity.
            storage: Byte count to express memory or storage capacity.

        Returns:
            Response data
        """
        path = f"/v1/system/silos/{silo}/quotas"
        params = {}
        headers = {}
        json_data = {
            "cpus": cpus if cpus is not None else None,
            "memory": memory if memory is not None else None,
            "storage": storage if storage is not None else None,
        }
        json_data = {k: v for k, v in json_data.items() if v is not None}

        response = self.parent._make_request(
            method="PUT",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
