# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class VpcUpdate:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def vpc_update(
        self,
        vpc: NameOrId,
        project: Optional[NameOrId] = None,
        description: Optional[str] = None,
        dns_name: Optional[Name] = None,
        name: Optional[Name] = None,
    ) -> Any:
        """


        Args:
            vpc: Name or ID of the VPC
            project: Name or ID of the project
            description: Updateable properties of a `Vpc`
            dns_name: Names must begin with a lower case ASCII letter, be composed exclusively of lowercase ASCII, uppercase ASCII, numbers, and '-', and may not end with a '-'. Names cannot be a UUID, but they may contain a UUID. They can be at most 63 characters long.
            name: Names must begin with a lower case ASCII letter, be composed exclusively of lowercase ASCII, uppercase ASCII, numbers, and '-', and may not end with a '-'. Names cannot be a UUID, but they may contain a UUID. They can be at most 63 characters long.

        Returns:
            Response data
        """
        path = f"/v1/vpcs/{vpc}"
        params = {}
        headers = {}
        if project is not None:
            params["project"] = project
        json_data = {
            "description": description if description is not None else None,
            "dns_name": dns_name if dns_name is not None else None,
            "name": name if name is not None else None,
        }
        json_data = {k: v for k, v in json_data.items() if v is not None}

        response = self.parent._make_request(
            method="PUT",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
