# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class InstanceUpdate:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def instance_update(
        self,
        instance: NameOrId,
        memory: ByteCount,
        ncpus: InstanceCpuCount,
        project: Optional[NameOrId] = None,
        auto_restart_policy: Optional[InstanceAutoRestartPolicy] = None,
        boot_disk: Optional[NameOrId] = None,
    ) -> Any:
        """


        Args:
            instance: Name or ID of the instance
            memory: Byte count to express memory or storage capacity.
            ncpus: The number of CPUs in an Instance
            project: Name or ID of the project
            auto_restart_policy: The instance should not be automatically restarted by the control plane if it fails.
            boot_disk: No description provided

        Returns:
            Response data
        """
        path = f"/v1/instances/{instance}"
        params = {}
        headers = {}
        if project is not None:
            params["project"] = project
        json_data = {
            "auto_restart_policy": (
                auto_restart_policy if auto_restart_policy is not None else None
            ),
            "boot_disk": boot_disk if boot_disk is not None else None,
            "memory": memory if memory is not None else None,
            "ncpus": ncpus if ncpus is not None else None,
        }
        json_data = {k: v for k, v in json_data.items() if v is not None}

        response = self.parent._make_request(
            method="PUT",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
