# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...trieve_api import TrieveApi


class CreateSetupCheckoutSession:
    def __init__(self, parent: "TrieveApi"):
        self.parent = parent

    def create_setup_checkout_session(
        self,
        organization_id: str,
    ) -> Any:
        """
        Create a checkout session (setup)

        Args:
            organization_id: The id of the organization to create setup checkout session for.

        Returns:
            Response data
        """
        path = f"/api/stripe/checkout/setup/{organization_id}"
        params = {}
        headers = {}
        json_data = None

        response = self.parent._make_request(
            method="POST",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
