# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ...models.models import *

from .login.login import Login
from .logout.logout import Logout
from .callback.callback import Callback
from .get_me.get_me import GetMe

if TYPE_CHECKING:
    from ..trieve_api import TrieveApi


class Auth:
    def __init__(self, parent: "TrieveApi"):
        """
        Authentication endpoint. Serves to register and authenticate users.

        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.login = Login(parent=parent).login
        self.logout = Logout(parent=parent).logout
        self.callback = Callback(parent=parent).callback
        self.get_me = GetMe(parent=parent).get_me
