# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...trieve_api import TrieveApi


class DeleteCrawlRequest:
    def __init__(self, parent: "TrieveApi"):
        self.parent = parent

    def delete_crawl_request(
        self,
        tr_dataset: str,
        crawl_id: str,
    ) -> Any:
        """
        This endpoint is used to delete an existing crawl request for a dataset. The request payload should contain the crawl id to delete.

        Args:
            tr_dataset: The dataset id to use for the request
            crawl_id: The id of the crawl to delete

        Returns:
            Response data
        """
        path = f"/api/crawl/{crawl_id}"
        params = {}
        headers = {}
        if tr_dataset is not None:
            headers["TR-Dataset"] = tr_dataset
        json_data = None

        response = self.parent._make_request(
            method="DELETE",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
