# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...trieve_api import TrieveApi


class DeleteOrganization:
    def __init__(self, parent: "TrieveApi"):
        self.parent = parent

    def delete_organization(
        self,
        tr_organization: str,
        organization_id: str,
    ) -> Any:
        """
        Delete an organization by its id. The auth'ed user must be an owner of the organization to delete it.

        Args:
            tr_organization: The organization id to use for the request
            organization_id: The id of the organization you want to fetch.

        Returns:
            Response data
        """
        path = f"/api/organization/{organization_id}"
        params = {}
        headers = {}
        if tr_organization is not None:
            headers["TR-Organization"] = tr_organization
        json_data = None

        response = self.parent._make_request(
            method="DELETE",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
