# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...trieve_api import TrieveApi


class UpdateSubscriptionPlan:
    def __init__(self, parent: "TrieveApi"):
        self.parent = parent

    def update_subscription_plan(
        self,
        tr_organization: str,
        subscription_id: str,
        plan_id: str,
    ) -> Any:
        """
        Update a subscription to a new plan

        Args:
            tr_organization: The organization id to use for the request
            subscription_id: id of the subscription you want to update
            plan_id: id of the plan you want to subscribe to

        Returns:
            Response data
        """
        path = f"/api/stripe/subscription_plan/{subscription_id}/{plan_id}"
        params = {}
        headers = {}
        if tr_organization is not None:
            headers["TR-Organization"] = tr_organization
        json_data = None

        response = self.parent._make_request(
            method="PATCH",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
