# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class InstanceSerialConsoleStream:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def instance_serial_console_stream(
        self,
        instance: NameOrId,
        most_recent: Optional[int] = None,
        project: Optional[NameOrId] = None,
    ) -> Any:
        """


        Args:
            instance: Name or ID of the instance
            most_recent: Character index in the serial buffer from which to read, counting *backward* from the most recently buffered data retrieved from the instance.
            project: Name or ID of the project, only required if `instance` is provided as a `Name`

        Returns:
            Response data
        """
        path = f"/v1/instances/{instance}/serial-console/stream"
        params = {}
        headers = {}
        if most_recent is not None:
            params["most_recent"] = most_recent
        if project is not None:
            params["project"] = project
        json_data = None

        response = self.parent._make_request(
            method="GET",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
