# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ...models.models import *

from .post_invitation.post_invitation import PostInvitation
from .delete_invitation.delete_invitation import DeleteInvitation
from .get_invitations.get_invitations import GetInvitations

if TYPE_CHECKING:
    from ..trieve_api import TrieveApi


class Invitation:
    def __init__(self, parent: "TrieveApi"):
        """
        Invitation endpoint. Exists to invite users to an organization.

        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.post_invitation = PostInvitation(parent=parent).post_invitation
        self.delete_invitation = DeleteInvitation(parent=parent).delete_invitation
        self.get_invitations = GetInvitations(parent=parent).get_invitations
