# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class SupportBundleDelete:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def support_bundle_delete(
        self,
        support_bundle: str,
    ) -> Any:
        """
        May also be used to cancel a support bundle which is currently being collected, or to remove metadata for a support bundle that has failed.

        Args:
            support_bundle: ID of the support bundle

        Returns:
            Response data
        """
        path = f"/experimental/v1/system/support-bundles/{support_bundle}"
        params = {}
        headers = {}
        json_data = None

        response = self.parent._make_request(
            method="DELETE",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
