# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...trieve_api import TrieveApi


class GetOrganizationApiKeys:
    def __init__(self, parent: "TrieveApi"):
        self.parent = parent

    def get_organization_api_keys(
        self,
        tr_organization: str,
    ) -> Any:
        """
        Get the api keys which belong to the organization. The actual api key values are not returned, only the ids, names, and creation dates.

        Args:
            tr_organization: The organization id to use for the request.

        Returns:
            Response data
        """
        path = f"/api/organization/api_key"
        params = {}
        headers = {}
        if tr_organization is not None:
            headers["TR-Organization"] = tr_organization
        json_data = None

        response = self.parent._make_request(
            method="GET",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
