# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class LoginSaml:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def login_saml(
        self,
        provider_name: Name,
        silo_name: Name,
        request_body: Optional[any] = None,
    ) -> Any:
        """


        Args:
            provider_name:
            silo_name:
            request_body: Request body

        Returns:
            Response data
        """
        path = f"/login/{silo_name}/saml/{provider_name}"
        params = {}
        headers = {}
        json_data = request_body.model_dump() if request_body else None

        response = self.parent._make_request(
            method="POST",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
