# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...oxide_region_api import OxideRegionAPI


class IpPoolSiloUpdate:
    def __init__(self, parent: "OxideRegionAPI"):
        self.parent = parent

    def ip_pool_silo_update(
        self,
        pool: NameOrId,
        silo: NameOrId,
        is_default: bool,
    ) -> Any:
        """
        When a user asks for an IP (e.g., at instance create time) without specifying a pool, the IP comes from the default pool if a default is configured. When a pool is made the default for a silo, any existing default will remain linked to the silo, but will no longer be the default.

        Args:
            pool:
            silo:
            is_default: When a pool is the default for a silo, floating IPs and instance ephemeral IPs will come from that pool when no other pool is specified. There can be at most one default for a given silo, so when a pool is made default, an existing default will remain linked but will no longer be the default.

        Returns:
            Response data
        """
        path = f"/v1/system/ip-pools/{pool}/silos/{silo}"
        params = {}
        headers = {}
        json_data = {
            "is_default": is_default if is_default is not None else None,
        }
        json_data = {k: v for k, v in json_data.items() if v is not None}

        response = self.parent._make_request(
            method="PUT",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
