# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ....models.models import *

if TYPE_CHECKING:
    from ...trieve_api import TrieveApi


class DirectToPaymentLink:
    def __init__(self, parent: "TrieveApi"):
        self.parent = parent

    def direct_to_payment_link(
        self,
        plan_id: str,
        organization_id: str,
    ) -> Any:
        """
        Get a 303 SeeOther redirect link to the stripe checkout page for the plan and organization

        Args:
            plan_id: id of the plan you want to subscribe to
            organization_id: id of the organization you want to subscribe to the plan

        Returns:
            Response data
        """
        path = f"/api/stripe/payment_link/{plan_id}/{organization_id}"
        params = {}
        headers = {}
        json_data = None

        response = self.parent._make_request(
            method="GET",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
