# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ...models.models import *

from .device_auth_request.device_auth_request import DeviceAuthRequest
from .device_auth_confirm.device_auth_confirm import DeviceAuthConfirm
from .device_access_token.device_access_token import DeviceAccessToken
from .probe_list.probe_list import ProbeList
from .probe_create.probe_create import ProbeCreate
from .probe_view.probe_view import ProbeView
from .probe_delete.probe_delete import ProbeDelete
from .support_bundle_list.support_bundle_list import SupportBundleList
from .support_bundle_create.support_bundle_create import SupportBundleCreate
from .support_bundle_view.support_bundle_view import SupportBundleView
from .support_bundle_delete.support_bundle_delete import SupportBundleDelete
from .support_bundle_download.support_bundle_download import SupportBundleDownload
from .support_bundle_head.support_bundle_head import SupportBundleHead
from .support_bundle_download_file.support_bundle_download_file import (
    SupportBundleDownloadFile,
)
from .support_bundle_head_file.support_bundle_head_file import SupportBundleHeadFile
from .support_bundle_index.support_bundle_index import SupportBundleIndex
from .logout.logout import Logout
from .timeseries_query.timeseries_query import TimeseriesQuery

if TYPE_CHECKING:
    from ..oxide_region_api import OxideRegionAPI


class Hidden:
    def __init__(self, parent: "OxideRegionAPI"):
        """
        TODO operations that will not ship to customers

        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.device_auth_request = DeviceAuthRequest(parent=parent).device_auth_request
        self.device_auth_confirm = DeviceAuthConfirm(parent=parent).device_auth_confirm
        self.device_access_token = DeviceAccessToken(parent=parent).device_access_token
        self.probe_list = ProbeList(parent=parent).probe_list
        self.probe_create = ProbeCreate(parent=parent).probe_create
        self.probe_view = ProbeView(parent=parent).probe_view
        self.probe_delete = ProbeDelete(parent=parent).probe_delete
        self.support_bundle_list = SupportBundleList(parent=parent).support_bundle_list
        self.support_bundle_create = SupportBundleCreate(
            parent=parent
        ).support_bundle_create
        self.support_bundle_view = SupportBundleView(parent=parent).support_bundle_view
        self.support_bundle_delete = SupportBundleDelete(
            parent=parent
        ).support_bundle_delete
        self.support_bundle_download = SupportBundleDownload(
            parent=parent
        ).support_bundle_download
        self.support_bundle_head = SupportBundleHead(parent=parent).support_bundle_head
        self.support_bundle_download_file = SupportBundleDownloadFile(
            parent=parent
        ).support_bundle_download_file
        self.support_bundle_head_file = SupportBundleHeadFile(
            parent=parent
        ).support_bundle_head_file
        self.support_bundle_index = SupportBundleIndex(
            parent=parent
        ).support_bundle_index
        self.logout = Logout(parent=parent).logout
        self.timeseries_query = TimeseriesQuery(parent=parent).timeseries_query
