# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING
from ...models.models import *

from .get_crawl_requests_for_dataset.get_crawl_requests_for_dataset import (
    GetCrawlRequestsForDataset,
)
from .create_crawl.create_crawl import CreateCrawl
from .update_crawl_request.update_crawl_request import UpdateCrawlRequest
from .delete_crawl_request.delete_crawl_request import DeleteCrawlRequest

if TYPE_CHECKING:
    from ..trieve_api import TrieveApi


class Crawl:
    def __init__(self, parent: "TrieveApi"):
        """
        Crawl endpoint. Used to create and manage crawls for datasets.

        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.get_crawl_requests_for_dataset = GetCrawlRequestsForDataset(
            parent=parent
        ).get_crawl_requests_for_dataset
        self.create_crawl = CreateCrawl(parent=parent).create_crawl
        self.update_crawl_request = UpdateCrawlRequest(
            parent=parent
        ).update_crawl_request
        self.delete_crawl_request = DeleteCrawlRequest(
            parent=parent
        ).delete_crawl_request
